// source: terra/market/v1beta1/tx.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var gogoproto_gogo_pb = require('../../../gogoproto/gogo_pb.js');
goog.object.extend(proto, gogoproto_gogo_pb);
var cosmos_base_v1beta1_coin_pb = require('../../../cosmos/base/v1beta1/coin_pb.js');
goog.object.extend(proto, cosmos_base_v1beta1_coin_pb);
goog.exportSymbol('proto.terra.market.v1beta1.MsgSwap', null, global);
goog.exportSymbol('proto.terra.market.v1beta1.MsgSwapResponse', null, global);
goog.exportSymbol('proto.terra.market.v1beta1.MsgSwapSend', null, global);
goog.exportSymbol('proto.terra.market.v1beta1.MsgSwapSendResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.terra.market.v1beta1.MsgSwap = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.terra.market.v1beta1.MsgSwap, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.terra.market.v1beta1.MsgSwap.displayName = 'proto.terra.market.v1beta1.MsgSwap';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.terra.market.v1beta1.MsgSwapResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.terra.market.v1beta1.MsgSwapResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.terra.market.v1beta1.MsgSwapResponse.displayName = 'proto.terra.market.v1beta1.MsgSwapResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.terra.market.v1beta1.MsgSwapSend = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.terra.market.v1beta1.MsgSwapSend, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.terra.market.v1beta1.MsgSwapSend.displayName = 'proto.terra.market.v1beta1.MsgSwapSend';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.terra.market.v1beta1.MsgSwapSendResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.terra.market.v1beta1.MsgSwapSendResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.terra.market.v1beta1.MsgSwapSendResponse.displayName = 'proto.terra.market.v1beta1.MsgSwapSendResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.terra.market.v1beta1.MsgSwap.prototype.toObject = function(opt_includeInstance) {
  return proto.terra.market.v1beta1.MsgSwap.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.terra.market.v1beta1.MsgSwap} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.terra.market.v1beta1.MsgSwap.toObject = function(includeInstance, msg) {
  var f, obj = {
    trader: jspb.Message.getFieldWithDefault(msg, 1, ""),
    offerCoin: (f = msg.getOfferCoin()) && cosmos_base_v1beta1_coin_pb.Coin.toObject(includeInstance, f),
    askDenom: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.terra.market.v1beta1.MsgSwap}
 */
proto.terra.market.v1beta1.MsgSwap.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.terra.market.v1beta1.MsgSwap;
  return proto.terra.market.v1beta1.MsgSwap.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.terra.market.v1beta1.MsgSwap} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.terra.market.v1beta1.MsgSwap}
 */
proto.terra.market.v1beta1.MsgSwap.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTrader(value);
      break;
    case 2:
      var value = new cosmos_base_v1beta1_coin_pb.Coin;
      reader.readMessage(value,cosmos_base_v1beta1_coin_pb.Coin.deserializeBinaryFromReader);
      msg.setOfferCoin(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setAskDenom(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.terra.market.v1beta1.MsgSwap.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.terra.market.v1beta1.MsgSwap.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.terra.market.v1beta1.MsgSwap} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.terra.market.v1beta1.MsgSwap.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTrader();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getOfferCoin();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      cosmos_base_v1beta1_coin_pb.Coin.serializeBinaryToWriter
    );
  }
  f = message.getAskDenom();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string trader = 1;
 * @return {string}
 */
proto.terra.market.v1beta1.MsgSwap.prototype.getTrader = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.terra.market.v1beta1.MsgSwap} returns this
 */
proto.terra.market.v1beta1.MsgSwap.prototype.setTrader = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional cosmos.base.v1beta1.Coin offer_coin = 2;
 * @return {?proto.cosmos.base.v1beta1.Coin}
 */
proto.terra.market.v1beta1.MsgSwap.prototype.getOfferCoin = function() {
  return /** @type{?proto.cosmos.base.v1beta1.Coin} */ (
    jspb.Message.getWrapperField(this, cosmos_base_v1beta1_coin_pb.Coin, 2));
};


/**
 * @param {?proto.cosmos.base.v1beta1.Coin|undefined} value
 * @return {!proto.terra.market.v1beta1.MsgSwap} returns this
*/
proto.terra.market.v1beta1.MsgSwap.prototype.setOfferCoin = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.terra.market.v1beta1.MsgSwap} returns this
 */
proto.terra.market.v1beta1.MsgSwap.prototype.clearOfferCoin = function() {
  return this.setOfferCoin(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.terra.market.v1beta1.MsgSwap.prototype.hasOfferCoin = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string ask_denom = 3;
 * @return {string}
 */
proto.terra.market.v1beta1.MsgSwap.prototype.getAskDenom = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.terra.market.v1beta1.MsgSwap} returns this
 */
proto.terra.market.v1beta1.MsgSwap.prototype.setAskDenom = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.terra.market.v1beta1.MsgSwapResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.terra.market.v1beta1.MsgSwapResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.terra.market.v1beta1.MsgSwapResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.terra.market.v1beta1.MsgSwapResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    swapCoin: (f = msg.getSwapCoin()) && cosmos_base_v1beta1_coin_pb.Coin.toObject(includeInstance, f),
    swapFee: (f = msg.getSwapFee()) && cosmos_base_v1beta1_coin_pb.Coin.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.terra.market.v1beta1.MsgSwapResponse}
 */
proto.terra.market.v1beta1.MsgSwapResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.terra.market.v1beta1.MsgSwapResponse;
  return proto.terra.market.v1beta1.MsgSwapResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.terra.market.v1beta1.MsgSwapResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.terra.market.v1beta1.MsgSwapResponse}
 */
proto.terra.market.v1beta1.MsgSwapResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new cosmos_base_v1beta1_coin_pb.Coin;
      reader.readMessage(value,cosmos_base_v1beta1_coin_pb.Coin.deserializeBinaryFromReader);
      msg.setSwapCoin(value);
      break;
    case 2:
      var value = new cosmos_base_v1beta1_coin_pb.Coin;
      reader.readMessage(value,cosmos_base_v1beta1_coin_pb.Coin.deserializeBinaryFromReader);
      msg.setSwapFee(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.terra.market.v1beta1.MsgSwapResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.terra.market.v1beta1.MsgSwapResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.terra.market.v1beta1.MsgSwapResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.terra.market.v1beta1.MsgSwapResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSwapCoin();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      cosmos_base_v1beta1_coin_pb.Coin.serializeBinaryToWriter
    );
  }
  f = message.getSwapFee();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      cosmos_base_v1beta1_coin_pb.Coin.serializeBinaryToWriter
    );
  }
};


/**
 * optional cosmos.base.v1beta1.Coin swap_coin = 1;
 * @return {?proto.cosmos.base.v1beta1.Coin}
 */
proto.terra.market.v1beta1.MsgSwapResponse.prototype.getSwapCoin = function() {
  return /** @type{?proto.cosmos.base.v1beta1.Coin} */ (
    jspb.Message.getWrapperField(this, cosmos_base_v1beta1_coin_pb.Coin, 1));
};


/**
 * @param {?proto.cosmos.base.v1beta1.Coin|undefined} value
 * @return {!proto.terra.market.v1beta1.MsgSwapResponse} returns this
*/
proto.terra.market.v1beta1.MsgSwapResponse.prototype.setSwapCoin = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.terra.market.v1beta1.MsgSwapResponse} returns this
 */
proto.terra.market.v1beta1.MsgSwapResponse.prototype.clearSwapCoin = function() {
  return this.setSwapCoin(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.terra.market.v1beta1.MsgSwapResponse.prototype.hasSwapCoin = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional cosmos.base.v1beta1.Coin swap_fee = 2;
 * @return {?proto.cosmos.base.v1beta1.Coin}
 */
proto.terra.market.v1beta1.MsgSwapResponse.prototype.getSwapFee = function() {
  return /** @type{?proto.cosmos.base.v1beta1.Coin} */ (
    jspb.Message.getWrapperField(this, cosmos_base_v1beta1_coin_pb.Coin, 2));
};


/**
 * @param {?proto.cosmos.base.v1beta1.Coin|undefined} value
 * @return {!proto.terra.market.v1beta1.MsgSwapResponse} returns this
*/
proto.terra.market.v1beta1.MsgSwapResponse.prototype.setSwapFee = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.terra.market.v1beta1.MsgSwapResponse} returns this
 */
proto.terra.market.v1beta1.MsgSwapResponse.prototype.clearSwapFee = function() {
  return this.setSwapFee(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.terra.market.v1beta1.MsgSwapResponse.prototype.hasSwapFee = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.terra.market.v1beta1.MsgSwapSend.prototype.toObject = function(opt_includeInstance) {
  return proto.terra.market.v1beta1.MsgSwapSend.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.terra.market.v1beta1.MsgSwapSend} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.terra.market.v1beta1.MsgSwapSend.toObject = function(includeInstance, msg) {
  var f, obj = {
    fromAddress: jspb.Message.getFieldWithDefault(msg, 1, ""),
    toAddress: jspb.Message.getFieldWithDefault(msg, 2, ""),
    offerCoin: (f = msg.getOfferCoin()) && cosmos_base_v1beta1_coin_pb.Coin.toObject(includeInstance, f),
    askDenom: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.terra.market.v1beta1.MsgSwapSend}
 */
proto.terra.market.v1beta1.MsgSwapSend.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.terra.market.v1beta1.MsgSwapSend;
  return proto.terra.market.v1beta1.MsgSwapSend.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.terra.market.v1beta1.MsgSwapSend} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.terra.market.v1beta1.MsgSwapSend}
 */
proto.terra.market.v1beta1.MsgSwapSend.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setFromAddress(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setToAddress(value);
      break;
    case 3:
      var value = new cosmos_base_v1beta1_coin_pb.Coin;
      reader.readMessage(value,cosmos_base_v1beta1_coin_pb.Coin.deserializeBinaryFromReader);
      msg.setOfferCoin(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setAskDenom(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.terra.market.v1beta1.MsgSwapSend.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.terra.market.v1beta1.MsgSwapSend.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.terra.market.v1beta1.MsgSwapSend} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.terra.market.v1beta1.MsgSwapSend.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFromAddress();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getToAddress();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getOfferCoin();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      cosmos_base_v1beta1_coin_pb.Coin.serializeBinaryToWriter
    );
  }
  f = message.getAskDenom();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * optional string from_address = 1;
 * @return {string}
 */
proto.terra.market.v1beta1.MsgSwapSend.prototype.getFromAddress = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.terra.market.v1beta1.MsgSwapSend} returns this
 */
proto.terra.market.v1beta1.MsgSwapSend.prototype.setFromAddress = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string to_address = 2;
 * @return {string}
 */
proto.terra.market.v1beta1.MsgSwapSend.prototype.getToAddress = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.terra.market.v1beta1.MsgSwapSend} returns this
 */
proto.terra.market.v1beta1.MsgSwapSend.prototype.setToAddress = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional cosmos.base.v1beta1.Coin offer_coin = 3;
 * @return {?proto.cosmos.base.v1beta1.Coin}
 */
proto.terra.market.v1beta1.MsgSwapSend.prototype.getOfferCoin = function() {
  return /** @type{?proto.cosmos.base.v1beta1.Coin} */ (
    jspb.Message.getWrapperField(this, cosmos_base_v1beta1_coin_pb.Coin, 3));
};


/**
 * @param {?proto.cosmos.base.v1beta1.Coin|undefined} value
 * @return {!proto.terra.market.v1beta1.MsgSwapSend} returns this
*/
proto.terra.market.v1beta1.MsgSwapSend.prototype.setOfferCoin = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.terra.market.v1beta1.MsgSwapSend} returns this
 */
proto.terra.market.v1beta1.MsgSwapSend.prototype.clearOfferCoin = function() {
  return this.setOfferCoin(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.terra.market.v1beta1.MsgSwapSend.prototype.hasOfferCoin = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional string ask_denom = 4;
 * @return {string}
 */
proto.terra.market.v1beta1.MsgSwapSend.prototype.getAskDenom = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.terra.market.v1beta1.MsgSwapSend} returns this
 */
proto.terra.market.v1beta1.MsgSwapSend.prototype.setAskDenom = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.terra.market.v1beta1.MsgSwapSendResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.terra.market.v1beta1.MsgSwapSendResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.terra.market.v1beta1.MsgSwapSendResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.terra.market.v1beta1.MsgSwapSendResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    swapCoin: (f = msg.getSwapCoin()) && cosmos_base_v1beta1_coin_pb.Coin.toObject(includeInstance, f),
    swapFee: (f = msg.getSwapFee()) && cosmos_base_v1beta1_coin_pb.Coin.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.terra.market.v1beta1.MsgSwapSendResponse}
 */
proto.terra.market.v1beta1.MsgSwapSendResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.terra.market.v1beta1.MsgSwapSendResponse;
  return proto.terra.market.v1beta1.MsgSwapSendResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.terra.market.v1beta1.MsgSwapSendResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.terra.market.v1beta1.MsgSwapSendResponse}
 */
proto.terra.market.v1beta1.MsgSwapSendResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new cosmos_base_v1beta1_coin_pb.Coin;
      reader.readMessage(value,cosmos_base_v1beta1_coin_pb.Coin.deserializeBinaryFromReader);
      msg.setSwapCoin(value);
      break;
    case 2:
      var value = new cosmos_base_v1beta1_coin_pb.Coin;
      reader.readMessage(value,cosmos_base_v1beta1_coin_pb.Coin.deserializeBinaryFromReader);
      msg.setSwapFee(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.terra.market.v1beta1.MsgSwapSendResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.terra.market.v1beta1.MsgSwapSendResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.terra.market.v1beta1.MsgSwapSendResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.terra.market.v1beta1.MsgSwapSendResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSwapCoin();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      cosmos_base_v1beta1_coin_pb.Coin.serializeBinaryToWriter
    );
  }
  f = message.getSwapFee();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      cosmos_base_v1beta1_coin_pb.Coin.serializeBinaryToWriter
    );
  }
};


/**
 * optional cosmos.base.v1beta1.Coin swap_coin = 1;
 * @return {?proto.cosmos.base.v1beta1.Coin}
 */
proto.terra.market.v1beta1.MsgSwapSendResponse.prototype.getSwapCoin = function() {
  return /** @type{?proto.cosmos.base.v1beta1.Coin} */ (
    jspb.Message.getWrapperField(this, cosmos_base_v1beta1_coin_pb.Coin, 1));
};


/**
 * @param {?proto.cosmos.base.v1beta1.Coin|undefined} value
 * @return {!proto.terra.market.v1beta1.MsgSwapSendResponse} returns this
*/
proto.terra.market.v1beta1.MsgSwapSendResponse.prototype.setSwapCoin = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.terra.market.v1beta1.MsgSwapSendResponse} returns this
 */
proto.terra.market.v1beta1.MsgSwapSendResponse.prototype.clearSwapCoin = function() {
  return this.setSwapCoin(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.terra.market.v1beta1.MsgSwapSendResponse.prototype.hasSwapCoin = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional cosmos.base.v1beta1.Coin swap_fee = 2;
 * @return {?proto.cosmos.base.v1beta1.Coin}
 */
proto.terra.market.v1beta1.MsgSwapSendResponse.prototype.getSwapFee = function() {
  return /** @type{?proto.cosmos.base.v1beta1.Coin} */ (
    jspb.Message.getWrapperField(this, cosmos_base_v1beta1_coin_pb.Coin, 2));
};


/**
 * @param {?proto.cosmos.base.v1beta1.Coin|undefined} value
 * @return {!proto.terra.market.v1beta1.MsgSwapSendResponse} returns this
*/
proto.terra.market.v1beta1.MsgSwapSendResponse.prototype.setSwapFee = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.terra.market.v1beta1.MsgSwapSendResponse} returns this
 */
proto.terra.market.v1beta1.MsgSwapSendResponse.prototype.clearSwapFee = function() {
  return this.setSwapFee(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.terra.market.v1beta1.MsgSwapSendResponse.prototype.hasSwapFee = function() {
  return jspb.Message.getField(this, 2) != null;
};


goog.object.extend(exports, proto.terra.market.v1beta1);
