//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: cosmos/crypto/secp256r1/keys.proto

package cosmos.crypto.secp256r1;

@kotlin.jvm.JvmSynthetic
inline fun pubKey(block: cosmos.crypto.secp256r1.PubKeyKt.Dsl.() -> Unit): cosmos.crypto.secp256r1.Keys.PubKey =
  cosmos.crypto.secp256r1.PubKeyKt.Dsl._create(cosmos.crypto.secp256r1.Keys.PubKey.newBuilder()).apply { block() }._build()
object PubKeyKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: cosmos.crypto.secp256r1.Keys.PubKey.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: cosmos.crypto.secp256r1.Keys.PubKey.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): cosmos.crypto.secp256r1.Keys.PubKey = _builder.build()

    /**
     * <pre>
     * Point on secp256r1 curve in a compressed representation as specified in section
     * 4.3.6 of ANSI X9.62: https://webstore.ansi.org/standards/ascx9/ansix9621998
     * </pre>
     *
     * <code>bytes key = 1 [(.gogoproto.customtype) = "ecdsaPK"];</code>
     */
    var key: com.google.protobuf.ByteString
      @JvmName("getKey")
      get() = _builder.getKey()
      @JvmName("setKey")
      set(value) {
        _builder.setKey(value)
      }
    /**
     * <pre>
     * Point on secp256r1 curve in a compressed representation as specified in section
     * 4.3.6 of ANSI X9.62: https://webstore.ansi.org/standards/ascx9/ansix9621998
     * </pre>
     *
     * <code>bytes key = 1 [(.gogoproto.customtype) = "ecdsaPK"];</code>
     */
    fun clearKey() {
      _builder.clearKey()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun cosmos.crypto.secp256r1.Keys.PubKey.copy(block: cosmos.crypto.secp256r1.PubKeyKt.Dsl.() -> Unit): cosmos.crypto.secp256r1.Keys.PubKey =
  cosmos.crypto.secp256r1.PubKeyKt.Dsl._create(this.toBuilder()).apply { block() }._build()
