//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: cosmos/gov/v1beta1/genesis.proto

package cosmos.gov.v1beta1;

@kotlin.jvm.JvmSynthetic
inline fun genesisState(block: cosmos.gov.v1beta1.GenesisStateKt.Dsl.() -> Unit): cosmos.gov.v1beta1.Genesis.GenesisState =
  cosmos.gov.v1beta1.GenesisStateKt.Dsl._create(cosmos.gov.v1beta1.Genesis.GenesisState.newBuilder()).apply { block() }._build()
object GenesisStateKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: cosmos.gov.v1beta1.Genesis.GenesisState.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: cosmos.gov.v1beta1.Genesis.GenesisState.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): cosmos.gov.v1beta1.Genesis.GenesisState = _builder.build()

    /**
     * <pre>
     * starting_proposal_id is the ID of the starting proposal.
     * </pre>
     *
     * <code>uint64 starting_proposal_id = 1 [(.gogoproto.moretags) = "yaml:&#92;"starting_proposal_id&#92;""];</code>
     */
    var startingProposalId: kotlin.Long
      @JvmName("getStartingProposalId")
      get() = _builder.getStartingProposalId()
      @JvmName("setStartingProposalId")
      set(value) {
        _builder.setStartingProposalId(value)
      }
    /**
     * <pre>
     * starting_proposal_id is the ID of the starting proposal.
     * </pre>
     *
     * <code>uint64 starting_proposal_id = 1 [(.gogoproto.moretags) = "yaml:&#92;"starting_proposal_id&#92;""];</code>
     */
    fun clearStartingProposalId() {
      _builder.clearStartingProposalId()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    class DepositsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <pre>
     * deposits defines all the deposits present at genesis.
     * </pre>
     *
     * <code>repeated .cosmos.gov.v1beta1.Deposit deposits = 2 [(.gogoproto.nullable) = false, (.gogoproto.castrepeated) = "Deposits"];</code>
     */
     val deposits: com.google.protobuf.kotlin.DslList<cosmos.gov.v1beta1.Gov.Deposit, DepositsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getDepositsList()
      )
    /**
     * <pre>
     * deposits defines all the deposits present at genesis.
     * </pre>
     *
     * <code>repeated .cosmos.gov.v1beta1.Deposit deposits = 2 [(.gogoproto.nullable) = false, (.gogoproto.castrepeated) = "Deposits"];</code>
     * @param value The deposits to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addDeposits")
    fun com.google.protobuf.kotlin.DslList<cosmos.gov.v1beta1.Gov.Deposit, DepositsProxy>.add(value: cosmos.gov.v1beta1.Gov.Deposit) {
      _builder.addDeposits(value)
    }/**
     * <pre>
     * deposits defines all the deposits present at genesis.
     * </pre>
     *
     * <code>repeated .cosmos.gov.v1beta1.Deposit deposits = 2 [(.gogoproto.nullable) = false, (.gogoproto.castrepeated) = "Deposits"];</code>
     * @param value The deposits to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignDeposits")
    inline operator fun com.google.protobuf.kotlin.DslList<cosmos.gov.v1beta1.Gov.Deposit, DepositsProxy>.plusAssign(value: cosmos.gov.v1beta1.Gov.Deposit) {
      add(value)
    }/**
     * <pre>
     * deposits defines all the deposits present at genesis.
     * </pre>
     *
     * <code>repeated .cosmos.gov.v1beta1.Deposit deposits = 2 [(.gogoproto.nullable) = false, (.gogoproto.castrepeated) = "Deposits"];</code>
     * @param values The deposits to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllDeposits")
    fun com.google.protobuf.kotlin.DslList<cosmos.gov.v1beta1.Gov.Deposit, DepositsProxy>.addAll(values: kotlin.collections.Iterable<cosmos.gov.v1beta1.Gov.Deposit>) {
      _builder.addAllDeposits(values)
    }/**
     * <pre>
     * deposits defines all the deposits present at genesis.
     * </pre>
     *
     * <code>repeated .cosmos.gov.v1beta1.Deposit deposits = 2 [(.gogoproto.nullable) = false, (.gogoproto.castrepeated) = "Deposits"];</code>
     * @param values The deposits to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllDeposits")
    inline operator fun com.google.protobuf.kotlin.DslList<cosmos.gov.v1beta1.Gov.Deposit, DepositsProxy>.plusAssign(values: kotlin.collections.Iterable<cosmos.gov.v1beta1.Gov.Deposit>) {
      addAll(values)
    }/**
     * <pre>
     * deposits defines all the deposits present at genesis.
     * </pre>
     *
     * <code>repeated .cosmos.gov.v1beta1.Deposit deposits = 2 [(.gogoproto.nullable) = false, (.gogoproto.castrepeated) = "Deposits"];</code>
     * @param index The index to set the value at.
     * @param value The deposits to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setDeposits")
    operator fun com.google.protobuf.kotlin.DslList<cosmos.gov.v1beta1.Gov.Deposit, DepositsProxy>.set(index: kotlin.Int, value: cosmos.gov.v1beta1.Gov.Deposit) {
      _builder.setDeposits(index, value)
    }/**
     * <pre>
     * deposits defines all the deposits present at genesis.
     * </pre>
     *
     * <code>repeated .cosmos.gov.v1beta1.Deposit deposits = 2 [(.gogoproto.nullable) = false, (.gogoproto.castrepeated) = "Deposits"];</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearDeposits")
    fun com.google.protobuf.kotlin.DslList<cosmos.gov.v1beta1.Gov.Deposit, DepositsProxy>.clear() {
      _builder.clearDeposits()
    }
    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    class VotesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <pre>
     * votes defines all the votes present at genesis.
     * </pre>
     *
     * <code>repeated .cosmos.gov.v1beta1.Vote votes = 3 [(.gogoproto.nullable) = false, (.gogoproto.castrepeated) = "Votes"];</code>
     */
     val votes: com.google.protobuf.kotlin.DslList<cosmos.gov.v1beta1.Gov.Vote, VotesProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getVotesList()
      )
    /**
     * <pre>
     * votes defines all the votes present at genesis.
     * </pre>
     *
     * <code>repeated .cosmos.gov.v1beta1.Vote votes = 3 [(.gogoproto.nullable) = false, (.gogoproto.castrepeated) = "Votes"];</code>
     * @param value The votes to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addVotes")
    fun com.google.protobuf.kotlin.DslList<cosmos.gov.v1beta1.Gov.Vote, VotesProxy>.add(value: cosmos.gov.v1beta1.Gov.Vote) {
      _builder.addVotes(value)
    }/**
     * <pre>
     * votes defines all the votes present at genesis.
     * </pre>
     *
     * <code>repeated .cosmos.gov.v1beta1.Vote votes = 3 [(.gogoproto.nullable) = false, (.gogoproto.castrepeated) = "Votes"];</code>
     * @param value The votes to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignVotes")
    inline operator fun com.google.protobuf.kotlin.DslList<cosmos.gov.v1beta1.Gov.Vote, VotesProxy>.plusAssign(value: cosmos.gov.v1beta1.Gov.Vote) {
      add(value)
    }/**
     * <pre>
     * votes defines all the votes present at genesis.
     * </pre>
     *
     * <code>repeated .cosmos.gov.v1beta1.Vote votes = 3 [(.gogoproto.nullable) = false, (.gogoproto.castrepeated) = "Votes"];</code>
     * @param values The votes to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllVotes")
    fun com.google.protobuf.kotlin.DslList<cosmos.gov.v1beta1.Gov.Vote, VotesProxy>.addAll(values: kotlin.collections.Iterable<cosmos.gov.v1beta1.Gov.Vote>) {
      _builder.addAllVotes(values)
    }/**
     * <pre>
     * votes defines all the votes present at genesis.
     * </pre>
     *
     * <code>repeated .cosmos.gov.v1beta1.Vote votes = 3 [(.gogoproto.nullable) = false, (.gogoproto.castrepeated) = "Votes"];</code>
     * @param values The votes to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllVotes")
    inline operator fun com.google.protobuf.kotlin.DslList<cosmos.gov.v1beta1.Gov.Vote, VotesProxy>.plusAssign(values: kotlin.collections.Iterable<cosmos.gov.v1beta1.Gov.Vote>) {
      addAll(values)
    }/**
     * <pre>
     * votes defines all the votes present at genesis.
     * </pre>
     *
     * <code>repeated .cosmos.gov.v1beta1.Vote votes = 3 [(.gogoproto.nullable) = false, (.gogoproto.castrepeated) = "Votes"];</code>
     * @param index The index to set the value at.
     * @param value The votes to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setVotes")
    operator fun com.google.protobuf.kotlin.DslList<cosmos.gov.v1beta1.Gov.Vote, VotesProxy>.set(index: kotlin.Int, value: cosmos.gov.v1beta1.Gov.Vote) {
      _builder.setVotes(index, value)
    }/**
     * <pre>
     * votes defines all the votes present at genesis.
     * </pre>
     *
     * <code>repeated .cosmos.gov.v1beta1.Vote votes = 3 [(.gogoproto.nullable) = false, (.gogoproto.castrepeated) = "Votes"];</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearVotes")
    fun com.google.protobuf.kotlin.DslList<cosmos.gov.v1beta1.Gov.Vote, VotesProxy>.clear() {
      _builder.clearVotes()
    }
    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    class ProposalsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <pre>
     * proposals defines all the proposals present at genesis.
     * </pre>
     *
     * <code>repeated .cosmos.gov.v1beta1.Proposal proposals = 4 [(.gogoproto.nullable) = false, (.gogoproto.castrepeated) = "Proposals"];</code>
     */
     val proposals: com.google.protobuf.kotlin.DslList<cosmos.gov.v1beta1.Gov.Proposal, ProposalsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getProposalsList()
      )
    /**
     * <pre>
     * proposals defines all the proposals present at genesis.
     * </pre>
     *
     * <code>repeated .cosmos.gov.v1beta1.Proposal proposals = 4 [(.gogoproto.nullable) = false, (.gogoproto.castrepeated) = "Proposals"];</code>
     * @param value The proposals to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addProposals")
    fun com.google.protobuf.kotlin.DslList<cosmos.gov.v1beta1.Gov.Proposal, ProposalsProxy>.add(value: cosmos.gov.v1beta1.Gov.Proposal) {
      _builder.addProposals(value)
    }/**
     * <pre>
     * proposals defines all the proposals present at genesis.
     * </pre>
     *
     * <code>repeated .cosmos.gov.v1beta1.Proposal proposals = 4 [(.gogoproto.nullable) = false, (.gogoproto.castrepeated) = "Proposals"];</code>
     * @param value The proposals to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignProposals")
    inline operator fun com.google.protobuf.kotlin.DslList<cosmos.gov.v1beta1.Gov.Proposal, ProposalsProxy>.plusAssign(value: cosmos.gov.v1beta1.Gov.Proposal) {
      add(value)
    }/**
     * <pre>
     * proposals defines all the proposals present at genesis.
     * </pre>
     *
     * <code>repeated .cosmos.gov.v1beta1.Proposal proposals = 4 [(.gogoproto.nullable) = false, (.gogoproto.castrepeated) = "Proposals"];</code>
     * @param values The proposals to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllProposals")
    fun com.google.protobuf.kotlin.DslList<cosmos.gov.v1beta1.Gov.Proposal, ProposalsProxy>.addAll(values: kotlin.collections.Iterable<cosmos.gov.v1beta1.Gov.Proposal>) {
      _builder.addAllProposals(values)
    }/**
     * <pre>
     * proposals defines all the proposals present at genesis.
     * </pre>
     *
     * <code>repeated .cosmos.gov.v1beta1.Proposal proposals = 4 [(.gogoproto.nullable) = false, (.gogoproto.castrepeated) = "Proposals"];</code>
     * @param values The proposals to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllProposals")
    inline operator fun com.google.protobuf.kotlin.DslList<cosmos.gov.v1beta1.Gov.Proposal, ProposalsProxy>.plusAssign(values: kotlin.collections.Iterable<cosmos.gov.v1beta1.Gov.Proposal>) {
      addAll(values)
    }/**
     * <pre>
     * proposals defines all the proposals present at genesis.
     * </pre>
     *
     * <code>repeated .cosmos.gov.v1beta1.Proposal proposals = 4 [(.gogoproto.nullable) = false, (.gogoproto.castrepeated) = "Proposals"];</code>
     * @param index The index to set the value at.
     * @param value The proposals to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setProposals")
    operator fun com.google.protobuf.kotlin.DslList<cosmos.gov.v1beta1.Gov.Proposal, ProposalsProxy>.set(index: kotlin.Int, value: cosmos.gov.v1beta1.Gov.Proposal) {
      _builder.setProposals(index, value)
    }/**
     * <pre>
     * proposals defines all the proposals present at genesis.
     * </pre>
     *
     * <code>repeated .cosmos.gov.v1beta1.Proposal proposals = 4 [(.gogoproto.nullable) = false, (.gogoproto.castrepeated) = "Proposals"];</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearProposals")
    fun com.google.protobuf.kotlin.DslList<cosmos.gov.v1beta1.Gov.Proposal, ProposalsProxy>.clear() {
      _builder.clearProposals()
    }
    /**
     * <pre>
     * params defines all the paramaters of related to deposit.
     * </pre>
     *
     * <code>.cosmos.gov.v1beta1.DepositParams deposit_params = 5 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"deposit_params&#92;""];</code>
     */
    var depositParams: cosmos.gov.v1beta1.Gov.DepositParams
      @JvmName("getDepositParams")
      get() = _builder.getDepositParams()
      @JvmName("setDepositParams")
      set(value) {
        _builder.setDepositParams(value)
      }
    /**
     * <pre>
     * params defines all the paramaters of related to deposit.
     * </pre>
     *
     * <code>.cosmos.gov.v1beta1.DepositParams deposit_params = 5 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"deposit_params&#92;""];</code>
     */
    fun clearDepositParams() {
      _builder.clearDepositParams()
    }
    /**
     * <pre>
     * params defines all the paramaters of related to deposit.
     * </pre>
     *
     * <code>.cosmos.gov.v1beta1.DepositParams deposit_params = 5 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"deposit_params&#92;""];</code>
     * @return Whether the depositParams field is set.
     */
    fun hasDepositParams(): kotlin.Boolean {
      return _builder.hasDepositParams()
    }

    /**
     * <pre>
     * params defines all the paramaters of related to voting.
     * </pre>
     *
     * <code>.cosmos.gov.v1beta1.VotingParams voting_params = 6 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"voting_params&#92;""];</code>
     */
    var votingParams: cosmos.gov.v1beta1.Gov.VotingParams
      @JvmName("getVotingParams")
      get() = _builder.getVotingParams()
      @JvmName("setVotingParams")
      set(value) {
        _builder.setVotingParams(value)
      }
    /**
     * <pre>
     * params defines all the paramaters of related to voting.
     * </pre>
     *
     * <code>.cosmos.gov.v1beta1.VotingParams voting_params = 6 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"voting_params&#92;""];</code>
     */
    fun clearVotingParams() {
      _builder.clearVotingParams()
    }
    /**
     * <pre>
     * params defines all the paramaters of related to voting.
     * </pre>
     *
     * <code>.cosmos.gov.v1beta1.VotingParams voting_params = 6 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"voting_params&#92;""];</code>
     * @return Whether the votingParams field is set.
     */
    fun hasVotingParams(): kotlin.Boolean {
      return _builder.hasVotingParams()
    }

    /**
     * <pre>
     * params defines all the paramaters of related to tally.
     * </pre>
     *
     * <code>.cosmos.gov.v1beta1.TallyParams tally_params = 7 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"tally_params&#92;""];</code>
     */
    var tallyParams: cosmos.gov.v1beta1.Gov.TallyParams
      @JvmName("getTallyParams")
      get() = _builder.getTallyParams()
      @JvmName("setTallyParams")
      set(value) {
        _builder.setTallyParams(value)
      }
    /**
     * <pre>
     * params defines all the paramaters of related to tally.
     * </pre>
     *
     * <code>.cosmos.gov.v1beta1.TallyParams tally_params = 7 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"tally_params&#92;""];</code>
     */
    fun clearTallyParams() {
      _builder.clearTallyParams()
    }
    /**
     * <pre>
     * params defines all the paramaters of related to tally.
     * </pre>
     *
     * <code>.cosmos.gov.v1beta1.TallyParams tally_params = 7 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"tally_params&#92;""];</code>
     * @return Whether the tallyParams field is set.
     */
    fun hasTallyParams(): kotlin.Boolean {
      return _builder.hasTallyParams()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun cosmos.gov.v1beta1.Genesis.GenesisState.copy(block: cosmos.gov.v1beta1.GenesisStateKt.Dsl.() -> Unit): cosmos.gov.v1beta1.Genesis.GenesisState =
  cosmos.gov.v1beta1.GenesisStateKt.Dsl._create(this.toBuilder()).apply { block() }._build()
