//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: cosmos/gov/v1beta1/tx.proto

package cosmos.gov.v1beta1;

@kotlin.jvm.JvmSynthetic
inline fun msgVote(block: cosmos.gov.v1beta1.MsgVoteKt.Dsl.() -> Unit): cosmos.gov.v1beta1.Tx.MsgVote =
  cosmos.gov.v1beta1.MsgVoteKt.Dsl._create(cosmos.gov.v1beta1.Tx.MsgVote.newBuilder()).apply { block() }._build()
object MsgVoteKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: cosmos.gov.v1beta1.Tx.MsgVote.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: cosmos.gov.v1beta1.Tx.MsgVote.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): cosmos.gov.v1beta1.Tx.MsgVote = _builder.build()

    /**
     * <code>uint64 proposal_id = 1 [(.gogoproto.jsontag) = "proposal_id", (.gogoproto.moretags) = "yaml:&#92;"proposal_id&#92;""];</code>
     */
    var proposalId: kotlin.Long
      @JvmName("getProposalId")
      get() = _builder.getProposalId()
      @JvmName("setProposalId")
      set(value) {
        _builder.setProposalId(value)
      }
    /**
     * <code>uint64 proposal_id = 1 [(.gogoproto.jsontag) = "proposal_id", (.gogoproto.moretags) = "yaml:&#92;"proposal_id&#92;""];</code>
     */
    fun clearProposalId() {
      _builder.clearProposalId()
    }

    /**
     * <code>string voter = 2;</code>
     */
    var voter: kotlin.String
      @JvmName("getVoter")
      get() = _builder.getVoter()
      @JvmName("setVoter")
      set(value) {
        _builder.setVoter(value)
      }
    /**
     * <code>string voter = 2;</code>
     */
    fun clearVoter() {
      _builder.clearVoter()
    }

    /**
     * <code>.cosmos.gov.v1beta1.VoteOption option = 3;</code>
     */
    var option: cosmos.gov.v1beta1.Gov.VoteOption
      @JvmName("getOption")
      get() = _builder.getOption()
      @JvmName("setOption")
      set(value) {
        _builder.setOption(value)
      }
    /**
     * <code>.cosmos.gov.v1beta1.VoteOption option = 3;</code>
     */
    fun clearOption() {
      _builder.clearOption()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun cosmos.gov.v1beta1.Tx.MsgVote.copy(block: cosmos.gov.v1beta1.MsgVoteKt.Dsl.() -> Unit): cosmos.gov.v1beta1.Tx.MsgVote =
  cosmos.gov.v1beta1.MsgVoteKt.Dsl._create(this.toBuilder()).apply { block() }._build()
