//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: cosmos/gov/v1beta1/gov.proto

package cosmos.gov.v1beta1;

@kotlin.jvm.JvmSynthetic
inline fun tallyParams(block: cosmos.gov.v1beta1.TallyParamsKt.Dsl.() -> Unit): cosmos.gov.v1beta1.Gov.TallyParams =
  cosmos.gov.v1beta1.TallyParamsKt.Dsl._create(cosmos.gov.v1beta1.Gov.TallyParams.newBuilder()).apply { block() }._build()
object TallyParamsKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: cosmos.gov.v1beta1.Gov.TallyParams.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: cosmos.gov.v1beta1.Gov.TallyParams.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): cosmos.gov.v1beta1.Gov.TallyParams = _builder.build()

    /**
     * <pre>
     *  Minimum percentage of total stake needed to vote for a result to be
     *  considered valid.
     * </pre>
     *
     * <code>bytes quorum = 1 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec", (.gogoproto.jsontag) = "quorum,omitempty"];</code>
     */
    var quorum: com.google.protobuf.ByteString
      @JvmName("getQuorum")
      get() = _builder.getQuorum()
      @JvmName("setQuorum")
      set(value) {
        _builder.setQuorum(value)
      }
    /**
     * <pre>
     *  Minimum percentage of total stake needed to vote for a result to be
     *  considered valid.
     * </pre>
     *
     * <code>bytes quorum = 1 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec", (.gogoproto.jsontag) = "quorum,omitempty"];</code>
     */
    fun clearQuorum() {
      _builder.clearQuorum()
    }

    /**
     * <pre>
     *  Minimum proportion of Yes votes for proposal to pass. Default value: 0.5.
     * </pre>
     *
     * <code>bytes threshold = 2 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec", (.gogoproto.jsontag) = "threshold,omitempty"];</code>
     */
    var threshold: com.google.protobuf.ByteString
      @JvmName("getThreshold")
      get() = _builder.getThreshold()
      @JvmName("setThreshold")
      set(value) {
        _builder.setThreshold(value)
      }
    /**
     * <pre>
     *  Minimum proportion of Yes votes for proposal to pass. Default value: 0.5.
     * </pre>
     *
     * <code>bytes threshold = 2 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec", (.gogoproto.jsontag) = "threshold,omitempty"];</code>
     */
    fun clearThreshold() {
      _builder.clearThreshold()
    }

    /**
     * <pre>
     *  Minimum value of Veto votes to Total votes ratio for proposal to be
     *  vetoed. Default value: 1/3.
     * </pre>
     *
     * <code>bytes veto_threshold = 3 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec", (.gogoproto.jsontag) = "veto_threshold,omitempty", (.gogoproto.moretags) = "yaml:&#92;"veto_threshold&#92;""];</code>
     */
    var vetoThreshold: com.google.protobuf.ByteString
      @JvmName("getVetoThreshold")
      get() = _builder.getVetoThreshold()
      @JvmName("setVetoThreshold")
      set(value) {
        _builder.setVetoThreshold(value)
      }
    /**
     * <pre>
     *  Minimum value of Veto votes to Total votes ratio for proposal to be
     *  vetoed. Default value: 1/3.
     * </pre>
     *
     * <code>bytes veto_threshold = 3 [(.gogoproto.nullable) = false, (.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec", (.gogoproto.jsontag) = "veto_threshold,omitempty", (.gogoproto.moretags) = "yaml:&#92;"veto_threshold&#92;""];</code>
     */
    fun clearVetoThreshold() {
      _builder.clearVetoThreshold()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun cosmos.gov.v1beta1.Gov.TallyParams.copy(block: cosmos.gov.v1beta1.TallyParamsKt.Dsl.() -> Unit): cosmos.gov.v1beta1.Gov.TallyParams =
  cosmos.gov.v1beta1.TallyParamsKt.Dsl._create(this.toBuilder()).apply { block() }._build()
