//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: cosmos/slashing/v1beta1/query.proto

package cosmos.slashing.v1beta1;

@kotlin.jvm.JvmSynthetic
inline fun querySigningInfosRequest(block: cosmos.slashing.v1beta1.QuerySigningInfosRequestKt.Dsl.() -> Unit): cosmos.slashing.v1beta1.QueryOuterClass.QuerySigningInfosRequest =
  cosmos.slashing.v1beta1.QuerySigningInfosRequestKt.Dsl._create(cosmos.slashing.v1beta1.QueryOuterClass.QuerySigningInfosRequest.newBuilder()).apply { block() }._build()
object QuerySigningInfosRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: cosmos.slashing.v1beta1.QueryOuterClass.QuerySigningInfosRequest.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: cosmos.slashing.v1beta1.QueryOuterClass.QuerySigningInfosRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): cosmos.slashing.v1beta1.QueryOuterClass.QuerySigningInfosRequest = _builder.build()

    /**
     * <code>.cosmos.base.query.v1beta1.PageRequest pagination = 1;</code>
     */
    var pagination: cosmos.base.query.v1beta1.Pagination.PageRequest
      @JvmName("getPagination")
      get() = _builder.getPagination()
      @JvmName("setPagination")
      set(value) {
        _builder.setPagination(value)
      }
    /**
     * <code>.cosmos.base.query.v1beta1.PageRequest pagination = 1;</code>
     */
    fun clearPagination() {
      _builder.clearPagination()
    }
    /**
     * <code>.cosmos.base.query.v1beta1.PageRequest pagination = 1;</code>
     * @return Whether the pagination field is set.
     */
    fun hasPagination(): kotlin.Boolean {
      return _builder.hasPagination()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun cosmos.slashing.v1beta1.QueryOuterClass.QuerySigningInfosRequest.copy(block: cosmos.slashing.v1beta1.QuerySigningInfosRequestKt.Dsl.() -> Unit): cosmos.slashing.v1beta1.QueryOuterClass.QuerySigningInfosRequest =
  cosmos.slashing.v1beta1.QuerySigningInfosRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()
