//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: cosmos/base/reflection/v1beta1/reflection.proto

package cosmos.base.reflection.v1beta1;

@kotlin.jvm.JvmSynthetic
inline fun listImplementationsResponse(block: cosmos.base.reflection.v1beta1.ListImplementationsResponseKt.Dsl.() -> Unit): cosmos.base.reflection.v1beta1.Reflection.ListImplementationsResponse =
  cosmos.base.reflection.v1beta1.ListImplementationsResponseKt.Dsl._create(cosmos.base.reflection.v1beta1.Reflection.ListImplementationsResponse.newBuilder()).apply { block() }._build()
object ListImplementationsResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: cosmos.base.reflection.v1beta1.Reflection.ListImplementationsResponse.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: cosmos.base.reflection.v1beta1.Reflection.ListImplementationsResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): cosmos.base.reflection.v1beta1.Reflection.ListImplementationsResponse = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    class ImplementationMessageNamesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated string implementation_message_names = 1;</code>
     * @return A list containing the implementationMessageNames.
     */
    val implementationMessageNames: com.google.protobuf.kotlin.DslList<kotlin.String, ImplementationMessageNamesProxy>
      @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getImplementationMessageNamesList()
      )
    /**
     * <code>repeated string implementation_message_names = 1;</code>
     * @param value The implementationMessageNames to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addImplementationMessageNames")
    fun com.google.protobuf.kotlin.DslList<kotlin.String, ImplementationMessageNamesProxy>.add(value: kotlin.String) {
      _builder.addImplementationMessageNames(value)
    }
    /**
     * <code>repeated string implementation_message_names = 1;</code>
     * @param value The implementationMessageNames to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignImplementationMessageNames")
    operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ImplementationMessageNamesProxy>.plusAssign(value: kotlin.String) {
      _builder.addImplementationMessageNames(value)
    }
    /**
     * <code>repeated string implementation_message_names = 1;</code>
     * @param values The implementationMessageNames to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllImplementationMessageNames")
    fun com.google.protobuf.kotlin.DslList<kotlin.String, ImplementationMessageNamesProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllImplementationMessageNames(values)
    }
    /**
     * <code>repeated string implementation_message_names = 1;</code>
     * @param values The implementationMessageNames to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllImplementationMessageNames")
    operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ImplementationMessageNamesProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllImplementationMessageNames(values)
    }
    /**
     * <code>repeated string implementation_message_names = 1;</code>
     * @param index The index to set the value at.
     * @param value The implementationMessageNames to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setImplementationMessageNames")
    operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ImplementationMessageNamesProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setImplementationMessageNames(index, value)
    }/**
     * <code>repeated string implementation_message_names = 1;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearImplementationMessageNames")
    fun com.google.protobuf.kotlin.DslList<kotlin.String, ImplementationMessageNamesProxy>.clear() {
      _builder.clearImplementationMessageNames()
    }}
}
@kotlin.jvm.JvmSynthetic
inline fun cosmos.base.reflection.v1beta1.Reflection.ListImplementationsResponse.copy(block: cosmos.base.reflection.v1beta1.ListImplementationsResponseKt.Dsl.() -> Unit): cosmos.base.reflection.v1beta1.Reflection.ListImplementationsResponse =
  cosmos.base.reflection.v1beta1.ListImplementationsResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()
