//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: cosmos/base/reflection/v1beta1/reflection.proto

package cosmos.base.reflection.v1beta1;

@kotlin.jvm.JvmSynthetic
inline fun listAllInterfacesRequest(block: cosmos.base.reflection.v1beta1.ListAllInterfacesRequestKt.Dsl.() -> Unit): cosmos.base.reflection.v1beta1.Reflection.ListAllInterfacesRequest =
  cosmos.base.reflection.v1beta1.ListAllInterfacesRequestKt.Dsl._create(cosmos.base.reflection.v1beta1.Reflection.ListAllInterfacesRequest.newBuilder()).apply { block() }._build()
object ListAllInterfacesRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: cosmos.base.reflection.v1beta1.Reflection.ListAllInterfacesRequest.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: cosmos.base.reflection.v1beta1.Reflection.ListAllInterfacesRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): cosmos.base.reflection.v1beta1.Reflection.ListAllInterfacesRequest = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
inline fun cosmos.base.reflection.v1beta1.Reflection.ListAllInterfacesRequest.copy(block: cosmos.base.reflection.v1beta1.ListAllInterfacesRequestKt.Dsl.() -> Unit): cosmos.base.reflection.v1beta1.Reflection.ListAllInterfacesRequest =
  cosmos.base.reflection.v1beta1.ListAllInterfacesRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()
