//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: terra/oracle/v1beta1/query.proto

package terra.oracle.v1beta1;

@kotlin.jvm.JvmSynthetic
inline fun queryActivesRequest(block: terra.oracle.v1beta1.QueryActivesRequestKt.Dsl.() -> Unit): terra.oracle.v1beta1.QueryOuterClass.QueryActivesRequest =
  terra.oracle.v1beta1.QueryActivesRequestKt.Dsl._create(terra.oracle.v1beta1.QueryOuterClass.QueryActivesRequest.newBuilder()).apply { block() }._build()
object QueryActivesRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: terra.oracle.v1beta1.QueryOuterClass.QueryActivesRequest.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: terra.oracle.v1beta1.QueryOuterClass.QueryActivesRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): terra.oracle.v1beta1.QueryOuterClass.QueryActivesRequest = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
inline fun terra.oracle.v1beta1.QueryOuterClass.QueryActivesRequest.copy(block: terra.oracle.v1beta1.QueryActivesRequestKt.Dsl.() -> Unit): terra.oracle.v1beta1.QueryOuterClass.QueryActivesRequest =
  terra.oracle.v1beta1.QueryActivesRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()
