//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: ibc/core/connection/v1/tx.proto

package ibc.core.connection.v1;

@kotlin.jvm.JvmSynthetic
inline fun msgConnectionOpenTry(block: ibc.core.connection.v1.MsgConnectionOpenTryKt.Dsl.() -> Unit): ibc.core.connection.v1.Tx.MsgConnectionOpenTry =
  ibc.core.connection.v1.MsgConnectionOpenTryKt.Dsl._create(ibc.core.connection.v1.Tx.MsgConnectionOpenTry.newBuilder()).apply { block() }._build()
object MsgConnectionOpenTryKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: ibc.core.connection.v1.Tx.MsgConnectionOpenTry.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ibc.core.connection.v1.Tx.MsgConnectionOpenTry.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ibc.core.connection.v1.Tx.MsgConnectionOpenTry = _builder.build()

    /**
     * <code>string client_id = 1 [(.gogoproto.moretags) = "yaml:&#92;"client_id&#92;""];</code>
     */
    var clientId: kotlin.String
      @JvmName("getClientId")
      get() = _builder.getClientId()
      @JvmName("setClientId")
      set(value) {
        _builder.setClientId(value)
      }
    /**
     * <code>string client_id = 1 [(.gogoproto.moretags) = "yaml:&#92;"client_id&#92;""];</code>
     */
    fun clearClientId() {
      _builder.clearClientId()
    }

    /**
     * <pre>
     * in the case of crossing hello's, when both chains call OpenInit, we need
     * the connection identifier of the previous connection in state INIT
     * </pre>
     *
     * <code>string previous_connection_id = 2 [(.gogoproto.moretags) = "yaml:&#92;"previous_connection_id&#92;""];</code>
     */
    var previousConnectionId: kotlin.String
      @JvmName("getPreviousConnectionId")
      get() = _builder.getPreviousConnectionId()
      @JvmName("setPreviousConnectionId")
      set(value) {
        _builder.setPreviousConnectionId(value)
      }
    /**
     * <pre>
     * in the case of crossing hello's, when both chains call OpenInit, we need
     * the connection identifier of the previous connection in state INIT
     * </pre>
     *
     * <code>string previous_connection_id = 2 [(.gogoproto.moretags) = "yaml:&#92;"previous_connection_id&#92;""];</code>
     */
    fun clearPreviousConnectionId() {
      _builder.clearPreviousConnectionId()
    }

    /**
     * <code>.google.protobuf.Any client_state = 3 [(.gogoproto.moretags) = "yaml:&#92;"client_state&#92;""];</code>
     */
    var clientState: com.google.protobuf.Any
      @JvmName("getClientState")
      get() = _builder.getClientState()
      @JvmName("setClientState")
      set(value) {
        _builder.setClientState(value)
      }
    /**
     * <code>.google.protobuf.Any client_state = 3 [(.gogoproto.moretags) = "yaml:&#92;"client_state&#92;""];</code>
     */
    fun clearClientState() {
      _builder.clearClientState()
    }
    /**
     * <code>.google.protobuf.Any client_state = 3 [(.gogoproto.moretags) = "yaml:&#92;"client_state&#92;""];</code>
     * @return Whether the clientState field is set.
     */
    fun hasClientState(): kotlin.Boolean {
      return _builder.hasClientState()
    }

    /**
     * <code>.ibc.core.connection.v1.Counterparty counterparty = 4 [(.gogoproto.nullable) = false];</code>
     */
    var counterparty: ibc.core.connection.v1.Connection.Counterparty
      @JvmName("getCounterparty")
      get() = _builder.getCounterparty()
      @JvmName("setCounterparty")
      set(value) {
        _builder.setCounterparty(value)
      }
    /**
     * <code>.ibc.core.connection.v1.Counterparty counterparty = 4 [(.gogoproto.nullable) = false];</code>
     */
    fun clearCounterparty() {
      _builder.clearCounterparty()
    }
    /**
     * <code>.ibc.core.connection.v1.Counterparty counterparty = 4 [(.gogoproto.nullable) = false];</code>
     * @return Whether the counterparty field is set.
     */
    fun hasCounterparty(): kotlin.Boolean {
      return _builder.hasCounterparty()
    }

    /**
     * <code>uint64 delay_period = 5 [(.gogoproto.moretags) = "yaml:&#92;"delay_period&#92;""];</code>
     */
    var delayPeriod: kotlin.Long
      @JvmName("getDelayPeriod")
      get() = _builder.getDelayPeriod()
      @JvmName("setDelayPeriod")
      set(value) {
        _builder.setDelayPeriod(value)
      }
    /**
     * <code>uint64 delay_period = 5 [(.gogoproto.moretags) = "yaml:&#92;"delay_period&#92;""];</code>
     */
    fun clearDelayPeriod() {
      _builder.clearDelayPeriod()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    class CounterpartyVersionsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .ibc.core.connection.v1.Version counterparty_versions = 6 [(.gogoproto.moretags) = "yaml:&#92;"counterparty_versions&#92;""];</code>
     */
     val counterpartyVersions: com.google.protobuf.kotlin.DslList<ibc.core.connection.v1.Connection.Version, CounterpartyVersionsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getCounterpartyVersionsList()
      )
    /**
     * <code>repeated .ibc.core.connection.v1.Version counterparty_versions = 6 [(.gogoproto.moretags) = "yaml:&#92;"counterparty_versions&#92;""];</code>
     * @param value The counterpartyVersions to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addCounterpartyVersions")
    fun com.google.protobuf.kotlin.DslList<ibc.core.connection.v1.Connection.Version, CounterpartyVersionsProxy>.add(value: ibc.core.connection.v1.Connection.Version) {
      _builder.addCounterpartyVersions(value)
    }/**
     * <code>repeated .ibc.core.connection.v1.Version counterparty_versions = 6 [(.gogoproto.moretags) = "yaml:&#92;"counterparty_versions&#92;""];</code>
     * @param value The counterpartyVersions to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignCounterpartyVersions")
    inline operator fun com.google.protobuf.kotlin.DslList<ibc.core.connection.v1.Connection.Version, CounterpartyVersionsProxy>.plusAssign(value: ibc.core.connection.v1.Connection.Version) {
      add(value)
    }/**
     * <code>repeated .ibc.core.connection.v1.Version counterparty_versions = 6 [(.gogoproto.moretags) = "yaml:&#92;"counterparty_versions&#92;""];</code>
     * @param values The counterpartyVersions to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllCounterpartyVersions")
    fun com.google.protobuf.kotlin.DslList<ibc.core.connection.v1.Connection.Version, CounterpartyVersionsProxy>.addAll(values: kotlin.collections.Iterable<ibc.core.connection.v1.Connection.Version>) {
      _builder.addAllCounterpartyVersions(values)
    }/**
     * <code>repeated .ibc.core.connection.v1.Version counterparty_versions = 6 [(.gogoproto.moretags) = "yaml:&#92;"counterparty_versions&#92;""];</code>
     * @param values The counterpartyVersions to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllCounterpartyVersions")
    inline operator fun com.google.protobuf.kotlin.DslList<ibc.core.connection.v1.Connection.Version, CounterpartyVersionsProxy>.plusAssign(values: kotlin.collections.Iterable<ibc.core.connection.v1.Connection.Version>) {
      addAll(values)
    }/**
     * <code>repeated .ibc.core.connection.v1.Version counterparty_versions = 6 [(.gogoproto.moretags) = "yaml:&#92;"counterparty_versions&#92;""];</code>
     * @param index The index to set the value at.
     * @param value The counterpartyVersions to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setCounterpartyVersions")
    operator fun com.google.protobuf.kotlin.DslList<ibc.core.connection.v1.Connection.Version, CounterpartyVersionsProxy>.set(index: kotlin.Int, value: ibc.core.connection.v1.Connection.Version) {
      _builder.setCounterpartyVersions(index, value)
    }/**
     * <code>repeated .ibc.core.connection.v1.Version counterparty_versions = 6 [(.gogoproto.moretags) = "yaml:&#92;"counterparty_versions&#92;""];</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearCounterpartyVersions")
    fun com.google.protobuf.kotlin.DslList<ibc.core.connection.v1.Connection.Version, CounterpartyVersionsProxy>.clear() {
      _builder.clearCounterpartyVersions()
    }
    /**
     * <code>.ibc.core.client.v1.Height proof_height = 7 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"proof_height&#92;""];</code>
     */
    var proofHeight: ibc.core.client.v1.Client.Height
      @JvmName("getProofHeight")
      get() = _builder.getProofHeight()
      @JvmName("setProofHeight")
      set(value) {
        _builder.setProofHeight(value)
      }
    /**
     * <code>.ibc.core.client.v1.Height proof_height = 7 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"proof_height&#92;""];</code>
     */
    fun clearProofHeight() {
      _builder.clearProofHeight()
    }
    /**
     * <code>.ibc.core.client.v1.Height proof_height = 7 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"proof_height&#92;""];</code>
     * @return Whether the proofHeight field is set.
     */
    fun hasProofHeight(): kotlin.Boolean {
      return _builder.hasProofHeight()
    }

    /**
     * <pre>
     * proof of the initialization the connection on Chain A: `UNITIALIZED -&gt;
     * INIT`
     * </pre>
     *
     * <code>bytes proof_init = 8 [(.gogoproto.moretags) = "yaml:&#92;"proof_init&#92;""];</code>
     */
    var proofInit: com.google.protobuf.ByteString
      @JvmName("getProofInit")
      get() = _builder.getProofInit()
      @JvmName("setProofInit")
      set(value) {
        _builder.setProofInit(value)
      }
    /**
     * <pre>
     * proof of the initialization the connection on Chain A: `UNITIALIZED -&gt;
     * INIT`
     * </pre>
     *
     * <code>bytes proof_init = 8 [(.gogoproto.moretags) = "yaml:&#92;"proof_init&#92;""];</code>
     */
    fun clearProofInit() {
      _builder.clearProofInit()
    }

    /**
     * <pre>
     * proof of client state included in message
     * </pre>
     *
     * <code>bytes proof_client = 9 [(.gogoproto.moretags) = "yaml:&#92;"proof_client&#92;""];</code>
     */
    var proofClient: com.google.protobuf.ByteString
      @JvmName("getProofClient")
      get() = _builder.getProofClient()
      @JvmName("setProofClient")
      set(value) {
        _builder.setProofClient(value)
      }
    /**
     * <pre>
     * proof of client state included in message
     * </pre>
     *
     * <code>bytes proof_client = 9 [(.gogoproto.moretags) = "yaml:&#92;"proof_client&#92;""];</code>
     */
    fun clearProofClient() {
      _builder.clearProofClient()
    }

    /**
     * <pre>
     * proof of client consensus state
     * </pre>
     *
     * <code>bytes proof_consensus = 10 [(.gogoproto.moretags) = "yaml:&#92;"proof_consensus&#92;""];</code>
     */
    var proofConsensus: com.google.protobuf.ByteString
      @JvmName("getProofConsensus")
      get() = _builder.getProofConsensus()
      @JvmName("setProofConsensus")
      set(value) {
        _builder.setProofConsensus(value)
      }
    /**
     * <pre>
     * proof of client consensus state
     * </pre>
     *
     * <code>bytes proof_consensus = 10 [(.gogoproto.moretags) = "yaml:&#92;"proof_consensus&#92;""];</code>
     */
    fun clearProofConsensus() {
      _builder.clearProofConsensus()
    }

    /**
     * <code>.ibc.core.client.v1.Height consensus_height = 11 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"consensus_height&#92;""];</code>
     */
    var consensusHeight: ibc.core.client.v1.Client.Height
      @JvmName("getConsensusHeight")
      get() = _builder.getConsensusHeight()
      @JvmName("setConsensusHeight")
      set(value) {
        _builder.setConsensusHeight(value)
      }
    /**
     * <code>.ibc.core.client.v1.Height consensus_height = 11 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"consensus_height&#92;""];</code>
     */
    fun clearConsensusHeight() {
      _builder.clearConsensusHeight()
    }
    /**
     * <code>.ibc.core.client.v1.Height consensus_height = 11 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"consensus_height&#92;""];</code>
     * @return Whether the consensusHeight field is set.
     */
    fun hasConsensusHeight(): kotlin.Boolean {
      return _builder.hasConsensusHeight()
    }

    /**
     * <code>string signer = 12;</code>
     */
    var signer: kotlin.String
      @JvmName("getSigner")
      get() = _builder.getSigner()
      @JvmName("setSigner")
      set(value) {
        _builder.setSigner(value)
      }
    /**
     * <code>string signer = 12;</code>
     */
    fun clearSigner() {
      _builder.clearSigner()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun ibc.core.connection.v1.Tx.MsgConnectionOpenTry.copy(block: ibc.core.connection.v1.MsgConnectionOpenTryKt.Dsl.() -> Unit): ibc.core.connection.v1.Tx.MsgConnectionOpenTry =
  ibc.core.connection.v1.MsgConnectionOpenTryKt.Dsl._create(this.toBuilder()).apply { block() }._build()
