//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: ibc/core/connection/v1/connection.proto

package ibc.core.connection.v1;

@kotlin.jvm.JvmSynthetic
inline fun version(block: ibc.core.connection.v1.VersionKt.Dsl.() -> Unit): ibc.core.connection.v1.Connection.Version =
  ibc.core.connection.v1.VersionKt.Dsl._create(ibc.core.connection.v1.Connection.Version.newBuilder()).apply { block() }._build()
object VersionKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: ibc.core.connection.v1.Connection.Version.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ibc.core.connection.v1.Connection.Version.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ibc.core.connection.v1.Connection.Version = _builder.build()

    /**
     * <pre>
     * unique version identifier
     * </pre>
     *
     * <code>string identifier = 1;</code>
     */
    var identifier: kotlin.String
      @JvmName("getIdentifier")
      get() = _builder.getIdentifier()
      @JvmName("setIdentifier")
      set(value) {
        _builder.setIdentifier(value)
      }
    /**
     * <pre>
     * unique version identifier
     * </pre>
     *
     * <code>string identifier = 1;</code>
     */
    fun clearIdentifier() {
      _builder.clearIdentifier()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    class FeaturesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <pre>
     * list of features compatible with the specified identifier
     * </pre>
     *
     * <code>repeated string features = 2;</code>
     * @return A list containing the features.
     */
    val features: com.google.protobuf.kotlin.DslList<kotlin.String, FeaturesProxy>
      @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getFeaturesList()
      )
    /**
     * <pre>
     * list of features compatible with the specified identifier
     * </pre>
     *
     * <code>repeated string features = 2;</code>
     * @param value The features to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addFeatures")
    fun com.google.protobuf.kotlin.DslList<kotlin.String, FeaturesProxy>.add(value: kotlin.String) {
      _builder.addFeatures(value)
    }
    /**
     * <pre>
     * list of features compatible with the specified identifier
     * </pre>
     *
     * <code>repeated string features = 2;</code>
     * @param value The features to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignFeatures")
    operator fun com.google.protobuf.kotlin.DslList<kotlin.String, FeaturesProxy>.plusAssign(value: kotlin.String) {
      _builder.addFeatures(value)
    }
    /**
     * <pre>
     * list of features compatible with the specified identifier
     * </pre>
     *
     * <code>repeated string features = 2;</code>
     * @param values The features to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllFeatures")
    fun com.google.protobuf.kotlin.DslList<kotlin.String, FeaturesProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllFeatures(values)
    }
    /**
     * <pre>
     * list of features compatible with the specified identifier
     * </pre>
     *
     * <code>repeated string features = 2;</code>
     * @param values The features to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllFeatures")
    operator fun com.google.protobuf.kotlin.DslList<kotlin.String, FeaturesProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllFeatures(values)
    }
    /**
     * <pre>
     * list of features compatible with the specified identifier
     * </pre>
     *
     * <code>repeated string features = 2;</code>
     * @param index The index to set the value at.
     * @param value The features to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setFeatures")
    operator fun com.google.protobuf.kotlin.DslList<kotlin.String, FeaturesProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setFeatures(index, value)
    }/**
     * <pre>
     * list of features compatible with the specified identifier
     * </pre>
     *
     * <code>repeated string features = 2;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearFeatures")
    fun com.google.protobuf.kotlin.DslList<kotlin.String, FeaturesProxy>.clear() {
      _builder.clearFeatures()
    }}
}
@kotlin.jvm.JvmSynthetic
inline fun ibc.core.connection.v1.Connection.Version.copy(block: ibc.core.connection.v1.VersionKt.Dsl.() -> Unit): ibc.core.connection.v1.Connection.Version =
  ibc.core.connection.v1.VersionKt.Dsl._create(this.toBuilder()).apply { block() }._build()
