//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: google/api/http.proto

package com.google.api;

@kotlin.jvm.JvmSynthetic
inline fun httpRule(block: com.google.api.HttpRuleKt.Dsl.() -> Unit): com.google.api.HttpRule =
  com.google.api.HttpRuleKt.Dsl._create(com.google.api.HttpRule.newBuilder()).apply { block() }._build()
object HttpRuleKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: com.google.api.HttpRule.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.google.api.HttpRule.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.google.api.HttpRule = _builder.build()

    /**
     * <pre>
     * Selects methods to which this rule applies.
     * Refer to [selector][google.api.DocumentationRule.selector] for syntax details.
     * </pre>
     *
     * <code>string selector = 1;</code>
     */
    var selector: kotlin.String
      @JvmName("getSelector")
      get() = _builder.getSelector()
      @JvmName("setSelector")
      set(value) {
        _builder.setSelector(value)
      }
    /**
     * <pre>
     * Selects methods to which this rule applies.
     * Refer to [selector][google.api.DocumentationRule.selector] for syntax details.
     * </pre>
     *
     * <code>string selector = 1;</code>
     */
    fun clearSelector() {
      _builder.clearSelector()
    }

    /**
     * <pre>
     * Used for listing and getting information about resources.
     * </pre>
     *
     * <code>string get = 2;</code>
     */
    var get: kotlin.String
      @JvmName("getGet")
      get() = _builder.getGet()
      @JvmName("setGet")
      set(value) {
        _builder.setGet(value)
      }
    /**
     * <pre>
     * Used for listing and getting information about resources.
     * </pre>
     *
     * <code>string get = 2;</code>
     */
    fun clearGet() {
      _builder.clearGet()
    }
    /**
     * <pre>
     * Used for listing and getting information about resources.
     * </pre>
     *
     * <code>string get = 2;</code>
     * @return Whether the get field is set.
     */
    fun hasGet(): kotlin.Boolean {
      return _builder.hasGet()
    }

    /**
     * <pre>
     * Used for updating a resource.
     * </pre>
     *
     * <code>string put = 3;</code>
     */
    var put: kotlin.String
      @JvmName("getPut")
      get() = _builder.getPut()
      @JvmName("setPut")
      set(value) {
        _builder.setPut(value)
      }
    /**
     * <pre>
     * Used for updating a resource.
     * </pre>
     *
     * <code>string put = 3;</code>
     */
    fun clearPut() {
      _builder.clearPut()
    }
    /**
     * <pre>
     * Used for updating a resource.
     * </pre>
     *
     * <code>string put = 3;</code>
     * @return Whether the put field is set.
     */
    fun hasPut(): kotlin.Boolean {
      return _builder.hasPut()
    }

    /**
     * <pre>
     * Used for creating a resource.
     * </pre>
     *
     * <code>string post = 4;</code>
     */
    var post: kotlin.String
      @JvmName("getPost")
      get() = _builder.getPost()
      @JvmName("setPost")
      set(value) {
        _builder.setPost(value)
      }
    /**
     * <pre>
     * Used for creating a resource.
     * </pre>
     *
     * <code>string post = 4;</code>
     */
    fun clearPost() {
      _builder.clearPost()
    }
    /**
     * <pre>
     * Used for creating a resource.
     * </pre>
     *
     * <code>string post = 4;</code>
     * @return Whether the post field is set.
     */
    fun hasPost(): kotlin.Boolean {
      return _builder.hasPost()
    }

    /**
     * <pre>
     * Used for deleting a resource.
     * </pre>
     *
     * <code>string delete = 5;</code>
     */
    var delete: kotlin.String
      @JvmName("getDelete")
      get() = _builder.getDelete()
      @JvmName("setDelete")
      set(value) {
        _builder.setDelete(value)
      }
    /**
     * <pre>
     * Used for deleting a resource.
     * </pre>
     *
     * <code>string delete = 5;</code>
     */
    fun clearDelete() {
      _builder.clearDelete()
    }
    /**
     * <pre>
     * Used for deleting a resource.
     * </pre>
     *
     * <code>string delete = 5;</code>
     * @return Whether the delete field is set.
     */
    fun hasDelete(): kotlin.Boolean {
      return _builder.hasDelete()
    }

    /**
     * <pre>
     * Used for updating a resource.
     * </pre>
     *
     * <code>string patch = 6;</code>
     */
    var patch: kotlin.String
      @JvmName("getPatch")
      get() = _builder.getPatch()
      @JvmName("setPatch")
      set(value) {
        _builder.setPatch(value)
      }
    /**
     * <pre>
     * Used for updating a resource.
     * </pre>
     *
     * <code>string patch = 6;</code>
     */
    fun clearPatch() {
      _builder.clearPatch()
    }
    /**
     * <pre>
     * Used for updating a resource.
     * </pre>
     *
     * <code>string patch = 6;</code>
     * @return Whether the patch field is set.
     */
    fun hasPatch(): kotlin.Boolean {
      return _builder.hasPatch()
    }

    /**
     * <pre>
     * The custom pattern is used for specifying an HTTP method that is not
     * included in the `pattern` field, such as HEAD, or "*" to leave the
     * HTTP method unspecified for this rule. The wild-card rule is useful
     * for services that provide content to Web (HTML) clients.
     * </pre>
     *
     * <code>.google.api.CustomHttpPattern custom = 8;</code>
     */
    var custom: com.google.api.CustomHttpPattern
      @JvmName("getCustom")
      get() = _builder.getCustom()
      @JvmName("setCustom")
      set(value) {
        _builder.setCustom(value)
      }
    /**
     * <pre>
     * The custom pattern is used for specifying an HTTP method that is not
     * included in the `pattern` field, such as HEAD, or "*" to leave the
     * HTTP method unspecified for this rule. The wild-card rule is useful
     * for services that provide content to Web (HTML) clients.
     * </pre>
     *
     * <code>.google.api.CustomHttpPattern custom = 8;</code>
     */
    fun clearCustom() {
      _builder.clearCustom()
    }
    /**
     * <pre>
     * The custom pattern is used for specifying an HTTP method that is not
     * included in the `pattern` field, such as HEAD, or "*" to leave the
     * HTTP method unspecified for this rule. The wild-card rule is useful
     * for services that provide content to Web (HTML) clients.
     * </pre>
     *
     * <code>.google.api.CustomHttpPattern custom = 8;</code>
     * @return Whether the custom field is set.
     */
    fun hasCustom(): kotlin.Boolean {
      return _builder.hasCustom()
    }

    /**
     * <pre>
     * The name of the request field whose value is mapped to the HTTP body, or
     * `*` for mapping all fields not captured by the path pattern to the HTTP
     * body. NOTE: the referred field must not be a repeated field and must be
     * present at the top-level of request message type.
     * </pre>
     *
     * <code>string body = 7;</code>
     */
    var body: kotlin.String
      @JvmName("getBody")
      get() = _builder.getBody()
      @JvmName("setBody")
      set(value) {
        _builder.setBody(value)
      }
    /**
     * <pre>
     * The name of the request field whose value is mapped to the HTTP body, or
     * `*` for mapping all fields not captured by the path pattern to the HTTP
     * body. NOTE: the referred field must not be a repeated field and must be
     * present at the top-level of request message type.
     * </pre>
     *
     * <code>string body = 7;</code>
     */
    fun clearBody() {
      _builder.clearBody()
    }

    /**
     * <pre>
     * Optional. The name of the response field whose value is mapped to the HTTP
     * body of response. Other response fields are ignored. When
     * not set, the response message will be used as HTTP body of response.
     * </pre>
     *
     * <code>string response_body = 12;</code>
     */
    var responseBody: kotlin.String
      @JvmName("getResponseBody")
      get() = _builder.getResponseBody()
      @JvmName("setResponseBody")
      set(value) {
        _builder.setResponseBody(value)
      }
    /**
     * <pre>
     * Optional. The name of the response field whose value is mapped to the HTTP
     * body of response. Other response fields are ignored. When
     * not set, the response message will be used as HTTP body of response.
     * </pre>
     *
     * <code>string response_body = 12;</code>
     */
    fun clearResponseBody() {
      _builder.clearResponseBody()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    class AdditionalBindingsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <pre>
     * Additional HTTP bindings for the selector. Nested bindings must
     * not contain an `additional_bindings` field themselves (that is,
     * the nesting may only be one level deep).
     * </pre>
     *
     * <code>repeated .google.api.HttpRule additional_bindings = 11;</code>
     */
     val additionalBindings: com.google.protobuf.kotlin.DslList<com.google.api.HttpRule, AdditionalBindingsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getAdditionalBindingsList()
      )
    /**
     * <pre>
     * Additional HTTP bindings for the selector. Nested bindings must
     * not contain an `additional_bindings` field themselves (that is,
     * the nesting may only be one level deep).
     * </pre>
     *
     * <code>repeated .google.api.HttpRule additional_bindings = 11;</code>
     * @param value The additionalBindings to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAdditionalBindings")
    fun com.google.protobuf.kotlin.DslList<com.google.api.HttpRule, AdditionalBindingsProxy>.add(value: com.google.api.HttpRule) {
      _builder.addAdditionalBindings(value)
    }/**
     * <pre>
     * Additional HTTP bindings for the selector. Nested bindings must
     * not contain an `additional_bindings` field themselves (that is,
     * the nesting may only be one level deep).
     * </pre>
     *
     * <code>repeated .google.api.HttpRule additional_bindings = 11;</code>
     * @param value The additionalBindings to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAdditionalBindings")
    inline operator fun com.google.protobuf.kotlin.DslList<com.google.api.HttpRule, AdditionalBindingsProxy>.plusAssign(value: com.google.api.HttpRule) {
      add(value)
    }/**
     * <pre>
     * Additional HTTP bindings for the selector. Nested bindings must
     * not contain an `additional_bindings` field themselves (that is,
     * the nesting may only be one level deep).
     * </pre>
     *
     * <code>repeated .google.api.HttpRule additional_bindings = 11;</code>
     * @param values The additionalBindings to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllAdditionalBindings")
    fun com.google.protobuf.kotlin.DslList<com.google.api.HttpRule, AdditionalBindingsProxy>.addAll(values: kotlin.collections.Iterable<com.google.api.HttpRule>) {
      _builder.addAllAdditionalBindings(values)
    }/**
     * <pre>
     * Additional HTTP bindings for the selector. Nested bindings must
     * not contain an `additional_bindings` field themselves (that is,
     * the nesting may only be one level deep).
     * </pre>
     *
     * <code>repeated .google.api.HttpRule additional_bindings = 11;</code>
     * @param values The additionalBindings to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllAdditionalBindings")
    inline operator fun com.google.protobuf.kotlin.DslList<com.google.api.HttpRule, AdditionalBindingsProxy>.plusAssign(values: kotlin.collections.Iterable<com.google.api.HttpRule>) {
      addAll(values)
    }/**
     * <pre>
     * Additional HTTP bindings for the selector. Nested bindings must
     * not contain an `additional_bindings` field themselves (that is,
     * the nesting may only be one level deep).
     * </pre>
     *
     * <code>repeated .google.api.HttpRule additional_bindings = 11;</code>
     * @param index The index to set the value at.
     * @param value The additionalBindings to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setAdditionalBindings")
    operator fun com.google.protobuf.kotlin.DslList<com.google.api.HttpRule, AdditionalBindingsProxy>.set(index: kotlin.Int, value: com.google.api.HttpRule) {
      _builder.setAdditionalBindings(index, value)
    }/**
     * <pre>
     * Additional HTTP bindings for the selector. Nested bindings must
     * not contain an `additional_bindings` field themselves (that is,
     * the nesting may only be one level deep).
     * </pre>
     *
     * <code>repeated .google.api.HttpRule additional_bindings = 11;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearAdditionalBindings")
    fun com.google.protobuf.kotlin.DslList<com.google.api.HttpRule, AdditionalBindingsProxy>.clear() {
      _builder.clearAdditionalBindings()
    }val patternCase: com.google.api.HttpRule.PatternCase
      @JvmName("getPatternCase")
      get() = _builder.getPatternCase()

    fun clearPattern() {
      _builder.clearPattern()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun com.google.api.HttpRule.copy(block: com.google.api.HttpRuleKt.Dsl.() -> Unit): com.google.api.HttpRule =
  com.google.api.HttpRuleKt.Dsl._create(this.toBuilder()).apply { block() }._build()
