//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: ibc/core/channel/v1/channel.proto

package ibc.core.channel.v1;

@kotlin.jvm.JvmSynthetic
inline fun packet(block: ibc.core.channel.v1.PacketKt.Dsl.() -> Unit): ibc.core.channel.v1.ChannelOuterClass.Packet =
  ibc.core.channel.v1.PacketKt.Dsl._create(ibc.core.channel.v1.ChannelOuterClass.Packet.newBuilder()).apply { block() }._build()
object PacketKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: ibc.core.channel.v1.ChannelOuterClass.Packet.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ibc.core.channel.v1.ChannelOuterClass.Packet.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ibc.core.channel.v1.ChannelOuterClass.Packet = _builder.build()

    /**
     * <pre>
     * number corresponds to the order of sends and receives, where a Packet
     * with an earlier sequence number must be sent and received before a Packet
     * with a later sequence number.
     * </pre>
     *
     * <code>uint64 sequence = 1;</code>
     */
    var sequence: kotlin.Long
      @JvmName("getSequence")
      get() = _builder.getSequence()
      @JvmName("setSequence")
      set(value) {
        _builder.setSequence(value)
      }
    /**
     * <pre>
     * number corresponds to the order of sends and receives, where a Packet
     * with an earlier sequence number must be sent and received before a Packet
     * with a later sequence number.
     * </pre>
     *
     * <code>uint64 sequence = 1;</code>
     */
    fun clearSequence() {
      _builder.clearSequence()
    }

    /**
     * <pre>
     * identifies the port on the sending chain.
     * </pre>
     *
     * <code>string source_port = 2 [(.gogoproto.moretags) = "yaml:&#92;"source_port&#92;""];</code>
     */
    var sourcePort: kotlin.String
      @JvmName("getSourcePort")
      get() = _builder.getSourcePort()
      @JvmName("setSourcePort")
      set(value) {
        _builder.setSourcePort(value)
      }
    /**
     * <pre>
     * identifies the port on the sending chain.
     * </pre>
     *
     * <code>string source_port = 2 [(.gogoproto.moretags) = "yaml:&#92;"source_port&#92;""];</code>
     */
    fun clearSourcePort() {
      _builder.clearSourcePort()
    }

    /**
     * <pre>
     * identifies the channel end on the sending chain.
     * </pre>
     *
     * <code>string source_channel = 3 [(.gogoproto.moretags) = "yaml:&#92;"source_channel&#92;""];</code>
     */
    var sourceChannel: kotlin.String
      @JvmName("getSourceChannel")
      get() = _builder.getSourceChannel()
      @JvmName("setSourceChannel")
      set(value) {
        _builder.setSourceChannel(value)
      }
    /**
     * <pre>
     * identifies the channel end on the sending chain.
     * </pre>
     *
     * <code>string source_channel = 3 [(.gogoproto.moretags) = "yaml:&#92;"source_channel&#92;""];</code>
     */
    fun clearSourceChannel() {
      _builder.clearSourceChannel()
    }

    /**
     * <pre>
     * identifies the port on the receiving chain.
     * </pre>
     *
     * <code>string destination_port = 4 [(.gogoproto.moretags) = "yaml:&#92;"destination_port&#92;""];</code>
     */
    var destinationPort: kotlin.String
      @JvmName("getDestinationPort")
      get() = _builder.getDestinationPort()
      @JvmName("setDestinationPort")
      set(value) {
        _builder.setDestinationPort(value)
      }
    /**
     * <pre>
     * identifies the port on the receiving chain.
     * </pre>
     *
     * <code>string destination_port = 4 [(.gogoproto.moretags) = "yaml:&#92;"destination_port&#92;""];</code>
     */
    fun clearDestinationPort() {
      _builder.clearDestinationPort()
    }

    /**
     * <pre>
     * identifies the channel end on the receiving chain.
     * </pre>
     *
     * <code>string destination_channel = 5 [(.gogoproto.moretags) = "yaml:&#92;"destination_channel&#92;""];</code>
     */
    var destinationChannel: kotlin.String
      @JvmName("getDestinationChannel")
      get() = _builder.getDestinationChannel()
      @JvmName("setDestinationChannel")
      set(value) {
        _builder.setDestinationChannel(value)
      }
    /**
     * <pre>
     * identifies the channel end on the receiving chain.
     * </pre>
     *
     * <code>string destination_channel = 5 [(.gogoproto.moretags) = "yaml:&#92;"destination_channel&#92;""];</code>
     */
    fun clearDestinationChannel() {
      _builder.clearDestinationChannel()
    }

    /**
     * <pre>
     * actual opaque bytes transferred directly to the application module
     * </pre>
     *
     * <code>bytes data = 6;</code>
     */
    var data: com.google.protobuf.ByteString
      @JvmName("getData")
      get() = _builder.getData()
      @JvmName("setData")
      set(value) {
        _builder.setData(value)
      }
    /**
     * <pre>
     * actual opaque bytes transferred directly to the application module
     * </pre>
     *
     * <code>bytes data = 6;</code>
     */
    fun clearData() {
      _builder.clearData()
    }

    /**
     * <pre>
     * block height after which the packet times out
     * </pre>
     *
     * <code>.ibc.core.client.v1.Height timeout_height = 7 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"timeout_height&#92;""];</code>
     */
    var timeoutHeight: ibc.core.client.v1.Client.Height
      @JvmName("getTimeoutHeight")
      get() = _builder.getTimeoutHeight()
      @JvmName("setTimeoutHeight")
      set(value) {
        _builder.setTimeoutHeight(value)
      }
    /**
     * <pre>
     * block height after which the packet times out
     * </pre>
     *
     * <code>.ibc.core.client.v1.Height timeout_height = 7 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"timeout_height&#92;""];</code>
     */
    fun clearTimeoutHeight() {
      _builder.clearTimeoutHeight()
    }
    /**
     * <pre>
     * block height after which the packet times out
     * </pre>
     *
     * <code>.ibc.core.client.v1.Height timeout_height = 7 [(.gogoproto.nullable) = false, (.gogoproto.moretags) = "yaml:&#92;"timeout_height&#92;""];</code>
     * @return Whether the timeoutHeight field is set.
     */
    fun hasTimeoutHeight(): kotlin.Boolean {
      return _builder.hasTimeoutHeight()
    }

    /**
     * <pre>
     * block timestamp (in nanoseconds) after which the packet times out
     * </pre>
     *
     * <code>uint64 timeout_timestamp = 8 [(.gogoproto.moretags) = "yaml:&#92;"timeout_timestamp&#92;""];</code>
     */
    var timeoutTimestamp: kotlin.Long
      @JvmName("getTimeoutTimestamp")
      get() = _builder.getTimeoutTimestamp()
      @JvmName("setTimeoutTimestamp")
      set(value) {
        _builder.setTimeoutTimestamp(value)
      }
    /**
     * <pre>
     * block timestamp (in nanoseconds) after which the packet times out
     * </pre>
     *
     * <code>uint64 timeout_timestamp = 8 [(.gogoproto.moretags) = "yaml:&#92;"timeout_timestamp&#92;""];</code>
     */
    fun clearTimeoutTimestamp() {
      _builder.clearTimeoutTimestamp()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun ibc.core.channel.v1.ChannelOuterClass.Packet.copy(block: ibc.core.channel.v1.PacketKt.Dsl.() -> Unit): ibc.core.channel.v1.ChannelOuterClass.Packet =
  ibc.core.channel.v1.PacketKt.Dsl._create(this.toBuilder()).apply { block() }._build()
