// source: terra/treasury/v1beta1/genesis.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var gogoproto_gogo_pb = require('../../../gogoproto/gogo_pb.js');
goog.object.extend(proto, gogoproto_gogo_pb);
var terra_treasury_v1beta1_treasury_pb = require('../../../terra/treasury/v1beta1/treasury_pb.js');
goog.object.extend(proto, terra_treasury_v1beta1_treasury_pb);
var cosmos_base_v1beta1_coin_pb = require('../../../cosmos/base/v1beta1/coin_pb.js');
goog.object.extend(proto, cosmos_base_v1beta1_coin_pb);
goog.exportSymbol('proto.terra.treasury.v1beta1.EpochState', null, global);
goog.exportSymbol('proto.terra.treasury.v1beta1.GenesisState', null, global);
goog.exportSymbol('proto.terra.treasury.v1beta1.TaxCap', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.terra.treasury.v1beta1.GenesisState = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.terra.treasury.v1beta1.GenesisState.repeatedFields_, null);
};
goog.inherits(proto.terra.treasury.v1beta1.GenesisState, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.terra.treasury.v1beta1.GenesisState.displayName = 'proto.terra.treasury.v1beta1.GenesisState';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.terra.treasury.v1beta1.TaxCap = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.terra.treasury.v1beta1.TaxCap, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.terra.treasury.v1beta1.TaxCap.displayName = 'proto.terra.treasury.v1beta1.TaxCap';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.terra.treasury.v1beta1.EpochState = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.terra.treasury.v1beta1.EpochState, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.terra.treasury.v1beta1.EpochState.displayName = 'proto.terra.treasury.v1beta1.EpochState';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.terra.treasury.v1beta1.GenesisState.repeatedFields_ = [4,5,6,7];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.terra.treasury.v1beta1.GenesisState.prototype.toObject = function(opt_includeInstance) {
  return proto.terra.treasury.v1beta1.GenesisState.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.terra.treasury.v1beta1.GenesisState} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.terra.treasury.v1beta1.GenesisState.toObject = function(includeInstance, msg) {
  var f, obj = {
    params: (f = msg.getParams()) && terra_treasury_v1beta1_treasury_pb.Params.toObject(includeInstance, f),
    taxRate: jspb.Message.getFieldWithDefault(msg, 2, ""),
    rewardWeight: jspb.Message.getFieldWithDefault(msg, 3, ""),
    taxCapsList: jspb.Message.toObjectList(msg.getTaxCapsList(),
    proto.terra.treasury.v1beta1.TaxCap.toObject, includeInstance),
    taxProceedsList: jspb.Message.toObjectList(msg.getTaxProceedsList(),
    cosmos_base_v1beta1_coin_pb.Coin.toObject, includeInstance),
    epochInitialIssuanceList: jspb.Message.toObjectList(msg.getEpochInitialIssuanceList(),
    cosmos_base_v1beta1_coin_pb.Coin.toObject, includeInstance),
    epochStatesList: jspb.Message.toObjectList(msg.getEpochStatesList(),
    proto.terra.treasury.v1beta1.EpochState.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.terra.treasury.v1beta1.GenesisState}
 */
proto.terra.treasury.v1beta1.GenesisState.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.terra.treasury.v1beta1.GenesisState;
  return proto.terra.treasury.v1beta1.GenesisState.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.terra.treasury.v1beta1.GenesisState} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.terra.treasury.v1beta1.GenesisState}
 */
proto.terra.treasury.v1beta1.GenesisState.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new terra_treasury_v1beta1_treasury_pb.Params;
      reader.readMessage(value,terra_treasury_v1beta1_treasury_pb.Params.deserializeBinaryFromReader);
      msg.setParams(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setTaxRate(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setRewardWeight(value);
      break;
    case 4:
      var value = new proto.terra.treasury.v1beta1.TaxCap;
      reader.readMessage(value,proto.terra.treasury.v1beta1.TaxCap.deserializeBinaryFromReader);
      msg.addTaxCaps(value);
      break;
    case 5:
      var value = new cosmos_base_v1beta1_coin_pb.Coin;
      reader.readMessage(value,cosmos_base_v1beta1_coin_pb.Coin.deserializeBinaryFromReader);
      msg.addTaxProceeds(value);
      break;
    case 6:
      var value = new cosmos_base_v1beta1_coin_pb.Coin;
      reader.readMessage(value,cosmos_base_v1beta1_coin_pb.Coin.deserializeBinaryFromReader);
      msg.addEpochInitialIssuance(value);
      break;
    case 7:
      var value = new proto.terra.treasury.v1beta1.EpochState;
      reader.readMessage(value,proto.terra.treasury.v1beta1.EpochState.deserializeBinaryFromReader);
      msg.addEpochStates(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.terra.treasury.v1beta1.GenesisState.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.terra.treasury.v1beta1.GenesisState.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.terra.treasury.v1beta1.GenesisState} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.terra.treasury.v1beta1.GenesisState.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getParams();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      terra_treasury_v1beta1_treasury_pb.Params.serializeBinaryToWriter
    );
  }
  f = message.getTaxRate();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getRewardWeight();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getTaxCapsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.terra.treasury.v1beta1.TaxCap.serializeBinaryToWriter
    );
  }
  f = message.getTaxProceedsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      cosmos_base_v1beta1_coin_pb.Coin.serializeBinaryToWriter
    );
  }
  f = message.getEpochInitialIssuanceList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      6,
      f,
      cosmos_base_v1beta1_coin_pb.Coin.serializeBinaryToWriter
    );
  }
  f = message.getEpochStatesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      7,
      f,
      proto.terra.treasury.v1beta1.EpochState.serializeBinaryToWriter
    );
  }
};


/**
 * optional Params params = 1;
 * @return {?proto.terra.treasury.v1beta1.Params}
 */
proto.terra.treasury.v1beta1.GenesisState.prototype.getParams = function() {
  return /** @type{?proto.terra.treasury.v1beta1.Params} */ (
    jspb.Message.getWrapperField(this, terra_treasury_v1beta1_treasury_pb.Params, 1));
};


/**
 * @param {?proto.terra.treasury.v1beta1.Params|undefined} value
 * @return {!proto.terra.treasury.v1beta1.GenesisState} returns this
*/
proto.terra.treasury.v1beta1.GenesisState.prototype.setParams = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.terra.treasury.v1beta1.GenesisState} returns this
 */
proto.terra.treasury.v1beta1.GenesisState.prototype.clearParams = function() {
  return this.setParams(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.terra.treasury.v1beta1.GenesisState.prototype.hasParams = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string tax_rate = 2;
 * @return {string}
 */
proto.terra.treasury.v1beta1.GenesisState.prototype.getTaxRate = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.terra.treasury.v1beta1.GenesisState} returns this
 */
proto.terra.treasury.v1beta1.GenesisState.prototype.setTaxRate = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string reward_weight = 3;
 * @return {string}
 */
proto.terra.treasury.v1beta1.GenesisState.prototype.getRewardWeight = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.terra.treasury.v1beta1.GenesisState} returns this
 */
proto.terra.treasury.v1beta1.GenesisState.prototype.setRewardWeight = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * repeated TaxCap tax_caps = 4;
 * @return {!Array<!proto.terra.treasury.v1beta1.TaxCap>}
 */
proto.terra.treasury.v1beta1.GenesisState.prototype.getTaxCapsList = function() {
  return /** @type{!Array<!proto.terra.treasury.v1beta1.TaxCap>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.terra.treasury.v1beta1.TaxCap, 4));
};


/**
 * @param {!Array<!proto.terra.treasury.v1beta1.TaxCap>} value
 * @return {!proto.terra.treasury.v1beta1.GenesisState} returns this
*/
proto.terra.treasury.v1beta1.GenesisState.prototype.setTaxCapsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.terra.treasury.v1beta1.TaxCap=} opt_value
 * @param {number=} opt_index
 * @return {!proto.terra.treasury.v1beta1.TaxCap}
 */
proto.terra.treasury.v1beta1.GenesisState.prototype.addTaxCaps = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.terra.treasury.v1beta1.TaxCap, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.terra.treasury.v1beta1.GenesisState} returns this
 */
proto.terra.treasury.v1beta1.GenesisState.prototype.clearTaxCapsList = function() {
  return this.setTaxCapsList([]);
};


/**
 * repeated cosmos.base.v1beta1.Coin tax_proceeds = 5;
 * @return {!Array<!proto.cosmos.base.v1beta1.Coin>}
 */
proto.terra.treasury.v1beta1.GenesisState.prototype.getTaxProceedsList = function() {
  return /** @type{!Array<!proto.cosmos.base.v1beta1.Coin>} */ (
    jspb.Message.getRepeatedWrapperField(this, cosmos_base_v1beta1_coin_pb.Coin, 5));
};


/**
 * @param {!Array<!proto.cosmos.base.v1beta1.Coin>} value
 * @return {!proto.terra.treasury.v1beta1.GenesisState} returns this
*/
proto.terra.treasury.v1beta1.GenesisState.prototype.setTaxProceedsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.cosmos.base.v1beta1.Coin=} opt_value
 * @param {number=} opt_index
 * @return {!proto.cosmos.base.v1beta1.Coin}
 */
proto.terra.treasury.v1beta1.GenesisState.prototype.addTaxProceeds = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.cosmos.base.v1beta1.Coin, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.terra.treasury.v1beta1.GenesisState} returns this
 */
proto.terra.treasury.v1beta1.GenesisState.prototype.clearTaxProceedsList = function() {
  return this.setTaxProceedsList([]);
};


/**
 * repeated cosmos.base.v1beta1.Coin epoch_initial_issuance = 6;
 * @return {!Array<!proto.cosmos.base.v1beta1.Coin>}
 */
proto.terra.treasury.v1beta1.GenesisState.prototype.getEpochInitialIssuanceList = function() {
  return /** @type{!Array<!proto.cosmos.base.v1beta1.Coin>} */ (
    jspb.Message.getRepeatedWrapperField(this, cosmos_base_v1beta1_coin_pb.Coin, 6));
};


/**
 * @param {!Array<!proto.cosmos.base.v1beta1.Coin>} value
 * @return {!proto.terra.treasury.v1beta1.GenesisState} returns this
*/
proto.terra.treasury.v1beta1.GenesisState.prototype.setEpochInitialIssuanceList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 6, value);
};


/**
 * @param {!proto.cosmos.base.v1beta1.Coin=} opt_value
 * @param {number=} opt_index
 * @return {!proto.cosmos.base.v1beta1.Coin}
 */
proto.terra.treasury.v1beta1.GenesisState.prototype.addEpochInitialIssuance = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 6, opt_value, proto.cosmos.base.v1beta1.Coin, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.terra.treasury.v1beta1.GenesisState} returns this
 */
proto.terra.treasury.v1beta1.GenesisState.prototype.clearEpochInitialIssuanceList = function() {
  return this.setEpochInitialIssuanceList([]);
};


/**
 * repeated EpochState epoch_states = 7;
 * @return {!Array<!proto.terra.treasury.v1beta1.EpochState>}
 */
proto.terra.treasury.v1beta1.GenesisState.prototype.getEpochStatesList = function() {
  return /** @type{!Array<!proto.terra.treasury.v1beta1.EpochState>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.terra.treasury.v1beta1.EpochState, 7));
};


/**
 * @param {!Array<!proto.terra.treasury.v1beta1.EpochState>} value
 * @return {!proto.terra.treasury.v1beta1.GenesisState} returns this
*/
proto.terra.treasury.v1beta1.GenesisState.prototype.setEpochStatesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 7, value);
};


/**
 * @param {!proto.terra.treasury.v1beta1.EpochState=} opt_value
 * @param {number=} opt_index
 * @return {!proto.terra.treasury.v1beta1.EpochState}
 */
proto.terra.treasury.v1beta1.GenesisState.prototype.addEpochStates = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 7, opt_value, proto.terra.treasury.v1beta1.EpochState, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.terra.treasury.v1beta1.GenesisState} returns this
 */
proto.terra.treasury.v1beta1.GenesisState.prototype.clearEpochStatesList = function() {
  return this.setEpochStatesList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.terra.treasury.v1beta1.TaxCap.prototype.toObject = function(opt_includeInstance) {
  return proto.terra.treasury.v1beta1.TaxCap.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.terra.treasury.v1beta1.TaxCap} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.terra.treasury.v1beta1.TaxCap.toObject = function(includeInstance, msg) {
  var f, obj = {
    denom: jspb.Message.getFieldWithDefault(msg, 1, ""),
    taxCap: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.terra.treasury.v1beta1.TaxCap}
 */
proto.terra.treasury.v1beta1.TaxCap.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.terra.treasury.v1beta1.TaxCap;
  return proto.terra.treasury.v1beta1.TaxCap.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.terra.treasury.v1beta1.TaxCap} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.terra.treasury.v1beta1.TaxCap}
 */
proto.terra.treasury.v1beta1.TaxCap.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setDenom(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setTaxCap(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.terra.treasury.v1beta1.TaxCap.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.terra.treasury.v1beta1.TaxCap.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.terra.treasury.v1beta1.TaxCap} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.terra.treasury.v1beta1.TaxCap.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDenom();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getTaxCap();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string denom = 1;
 * @return {string}
 */
proto.terra.treasury.v1beta1.TaxCap.prototype.getDenom = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.terra.treasury.v1beta1.TaxCap} returns this
 */
proto.terra.treasury.v1beta1.TaxCap.prototype.setDenom = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string tax_cap = 2;
 * @return {string}
 */
proto.terra.treasury.v1beta1.TaxCap.prototype.getTaxCap = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.terra.treasury.v1beta1.TaxCap} returns this
 */
proto.terra.treasury.v1beta1.TaxCap.prototype.setTaxCap = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.terra.treasury.v1beta1.EpochState.prototype.toObject = function(opt_includeInstance) {
  return proto.terra.treasury.v1beta1.EpochState.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.terra.treasury.v1beta1.EpochState} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.terra.treasury.v1beta1.EpochState.toObject = function(includeInstance, msg) {
  var f, obj = {
    epoch: jspb.Message.getFieldWithDefault(msg, 1, 0),
    taxReward: jspb.Message.getFieldWithDefault(msg, 2, ""),
    seigniorageReward: jspb.Message.getFieldWithDefault(msg, 3, ""),
    totalStakedLuna: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.terra.treasury.v1beta1.EpochState}
 */
proto.terra.treasury.v1beta1.EpochState.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.terra.treasury.v1beta1.EpochState;
  return proto.terra.treasury.v1beta1.EpochState.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.terra.treasury.v1beta1.EpochState} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.terra.treasury.v1beta1.EpochState}
 */
proto.terra.treasury.v1beta1.EpochState.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setEpoch(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setTaxReward(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setSeigniorageReward(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setTotalStakedLuna(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.terra.treasury.v1beta1.EpochState.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.terra.treasury.v1beta1.EpochState.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.terra.treasury.v1beta1.EpochState} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.terra.treasury.v1beta1.EpochState.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEpoch();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = message.getTaxReward();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getSeigniorageReward();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getTotalStakedLuna();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * optional uint64 epoch = 1;
 * @return {number}
 */
proto.terra.treasury.v1beta1.EpochState.prototype.getEpoch = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.terra.treasury.v1beta1.EpochState} returns this
 */
proto.terra.treasury.v1beta1.EpochState.prototype.setEpoch = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string tax_reward = 2;
 * @return {string}
 */
proto.terra.treasury.v1beta1.EpochState.prototype.getTaxReward = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.terra.treasury.v1beta1.EpochState} returns this
 */
proto.terra.treasury.v1beta1.EpochState.prototype.setTaxReward = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string seigniorage_reward = 3;
 * @return {string}
 */
proto.terra.treasury.v1beta1.EpochState.prototype.getSeigniorageReward = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.terra.treasury.v1beta1.EpochState} returns this
 */
proto.terra.treasury.v1beta1.EpochState.prototype.setSeigniorageReward = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string total_staked_luna = 4;
 * @return {string}
 */
proto.terra.treasury.v1beta1.EpochState.prototype.getTotalStakedLuna = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.terra.treasury.v1beta1.EpochState} returns this
 */
proto.terra.treasury.v1beta1.EpochState.prototype.setTotalStakedLuna = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


goog.object.extend(exports, proto.terra.treasury.v1beta1);
