//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: ibc/core/client/v1/client.proto

package ibc.core.client.v1;

@kotlin.jvm.JvmSynthetic
inline fun identifiedClientState(block: ibc.core.client.v1.IdentifiedClientStateKt.Dsl.() -> Unit): ibc.core.client.v1.Client.IdentifiedClientState =
  ibc.core.client.v1.IdentifiedClientStateKt.Dsl._create(ibc.core.client.v1.Client.IdentifiedClientState.newBuilder()).apply { block() }._build()
object IdentifiedClientStateKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: ibc.core.client.v1.Client.IdentifiedClientState.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ibc.core.client.v1.Client.IdentifiedClientState.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ibc.core.client.v1.Client.IdentifiedClientState = _builder.build()

    /**
     * <pre>
     * client identifier
     * </pre>
     *
     * <code>string client_id = 1 [(.gogoproto.moretags) = "yaml:&#92;"client_id&#92;""];</code>
     */
    var clientId: kotlin.String
      @JvmName("getClientId")
      get() = _builder.getClientId()
      @JvmName("setClientId")
      set(value) {
        _builder.setClientId(value)
      }
    /**
     * <pre>
     * client identifier
     * </pre>
     *
     * <code>string client_id = 1 [(.gogoproto.moretags) = "yaml:&#92;"client_id&#92;""];</code>
     */
    fun clearClientId() {
      _builder.clearClientId()
    }

    /**
     * <pre>
     * client state
     * </pre>
     *
     * <code>.google.protobuf.Any client_state = 2 [(.gogoproto.moretags) = "yaml:&#92;"client_state&#92;""];</code>
     */
    var clientState: com.google.protobuf.Any
      @JvmName("getClientState")
      get() = _builder.getClientState()
      @JvmName("setClientState")
      set(value) {
        _builder.setClientState(value)
      }
    /**
     * <pre>
     * client state
     * </pre>
     *
     * <code>.google.protobuf.Any client_state = 2 [(.gogoproto.moretags) = "yaml:&#92;"client_state&#92;""];</code>
     */
    fun clearClientState() {
      _builder.clearClientState()
    }
    /**
     * <pre>
     * client state
     * </pre>
     *
     * <code>.google.protobuf.Any client_state = 2 [(.gogoproto.moretags) = "yaml:&#92;"client_state&#92;""];</code>
     * @return Whether the clientState field is set.
     */
    fun hasClientState(): kotlin.Boolean {
      return _builder.hasClientState()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun ibc.core.client.v1.Client.IdentifiedClientState.copy(block: ibc.core.client.v1.IdentifiedClientStateKt.Dsl.() -> Unit): ibc.core.client.v1.Client.IdentifiedClientState =
  ibc.core.client.v1.IdentifiedClientStateKt.Dsl._create(this.toBuilder()).apply { block() }._build()
