//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: ibc/core/client/v1/query.proto

package ibc.core.client.v1;

@kotlin.jvm.JvmSynthetic
inline fun queryClientStatesRequest(block: ibc.core.client.v1.QueryClientStatesRequestKt.Dsl.() -> Unit): ibc.core.client.v1.QueryOuterClass.QueryClientStatesRequest =
  ibc.core.client.v1.QueryClientStatesRequestKt.Dsl._create(ibc.core.client.v1.QueryOuterClass.QueryClientStatesRequest.newBuilder()).apply { block() }._build()
object QueryClientStatesRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: ibc.core.client.v1.QueryOuterClass.QueryClientStatesRequest.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: ibc.core.client.v1.QueryOuterClass.QueryClientStatesRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): ibc.core.client.v1.QueryOuterClass.QueryClientStatesRequest = _builder.build()

    /**
     * <pre>
     * pagination request
     * </pre>
     *
     * <code>.cosmos.base.query.v1beta1.PageRequest pagination = 1;</code>
     */
    var pagination: cosmos.base.query.v1beta1.Pagination.PageRequest
      @JvmName("getPagination")
      get() = _builder.getPagination()
      @JvmName("setPagination")
      set(value) {
        _builder.setPagination(value)
      }
    /**
     * <pre>
     * pagination request
     * </pre>
     *
     * <code>.cosmos.base.query.v1beta1.PageRequest pagination = 1;</code>
     */
    fun clearPagination() {
      _builder.clearPagination()
    }
    /**
     * <pre>
     * pagination request
     * </pre>
     *
     * <code>.cosmos.base.query.v1beta1.PageRequest pagination = 1;</code>
     * @return Whether the pagination field is set.
     */
    fun hasPagination(): kotlin.Boolean {
      return _builder.hasPagination()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun ibc.core.client.v1.QueryOuterClass.QueryClientStatesRequest.copy(block: ibc.core.client.v1.QueryClientStatesRequestKt.Dsl.() -> Unit): ibc.core.client.v1.QueryOuterClass.QueryClientStatesRequest =
  ibc.core.client.v1.QueryClientStatesRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()
