//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: cosmos/staking/v1beta1/tx.proto

package cosmos.staking.v1beta1;

@kotlin.jvm.JvmSynthetic
inline fun msgEditValidator(block: cosmos.staking.v1beta1.MsgEditValidatorKt.Dsl.() -> Unit): cosmos.staking.v1beta1.Tx.MsgEditValidator =
  cosmos.staking.v1beta1.MsgEditValidatorKt.Dsl._create(cosmos.staking.v1beta1.Tx.MsgEditValidator.newBuilder()).apply { block() }._build()
object MsgEditValidatorKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: cosmos.staking.v1beta1.Tx.MsgEditValidator.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: cosmos.staking.v1beta1.Tx.MsgEditValidator.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): cosmos.staking.v1beta1.Tx.MsgEditValidator = _builder.build()

    /**
     * <code>.cosmos.staking.v1beta1.Description description = 1 [(.gogoproto.nullable) = false];</code>
     */
    var description: cosmos.staking.v1beta1.Staking.Description
      @JvmName("getDescription")
      get() = _builder.getDescription()
      @JvmName("setDescription")
      set(value) {
        _builder.setDescription(value)
      }
    /**
     * <code>.cosmos.staking.v1beta1.Description description = 1 [(.gogoproto.nullable) = false];</code>
     */
    fun clearDescription() {
      _builder.clearDescription()
    }
    /**
     * <code>.cosmos.staking.v1beta1.Description description = 1 [(.gogoproto.nullable) = false];</code>
     * @return Whether the description field is set.
     */
    fun hasDescription(): kotlin.Boolean {
      return _builder.hasDescription()
    }

    /**
     * <code>string validator_address = 2 [(.gogoproto.moretags) = "yaml:&#92;"address&#92;""];</code>
     */
    var validatorAddress: kotlin.String
      @JvmName("getValidatorAddress")
      get() = _builder.getValidatorAddress()
      @JvmName("setValidatorAddress")
      set(value) {
        _builder.setValidatorAddress(value)
      }
    /**
     * <code>string validator_address = 2 [(.gogoproto.moretags) = "yaml:&#92;"address&#92;""];</code>
     */
    fun clearValidatorAddress() {
      _builder.clearValidatorAddress()
    }

    /**
     * <pre>
     * We pass a reference to the new commission rate and min self delegation as
     * it's not mandatory to update. If not updated, the deserialized rate will be
     * zero with no way to distinguish if an update was intended.
     * REF: #2373
     * </pre>
     *
     * <code>string commission_rate = 3 [(.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec", (.gogoproto.moretags) = "yaml:&#92;"commission_rate&#92;""];</code>
     */
    var commissionRate: kotlin.String
      @JvmName("getCommissionRate")
      get() = _builder.getCommissionRate()
      @JvmName("setCommissionRate")
      set(value) {
        _builder.setCommissionRate(value)
      }
    /**
     * <pre>
     * We pass a reference to the new commission rate and min self delegation as
     * it's not mandatory to update. If not updated, the deserialized rate will be
     * zero with no way to distinguish if an update was intended.
     * REF: #2373
     * </pre>
     *
     * <code>string commission_rate = 3 [(.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Dec", (.gogoproto.moretags) = "yaml:&#92;"commission_rate&#92;""];</code>
     */
    fun clearCommissionRate() {
      _builder.clearCommissionRate()
    }

    /**
     * <code>string min_self_delegation = 4 [(.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Int", (.gogoproto.moretags) = "yaml:&#92;"min_self_delegation&#92;""];</code>
     */
    var minSelfDelegation: kotlin.String
      @JvmName("getMinSelfDelegation")
      get() = _builder.getMinSelfDelegation()
      @JvmName("setMinSelfDelegation")
      set(value) {
        _builder.setMinSelfDelegation(value)
      }
    /**
     * <code>string min_self_delegation = 4 [(.gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Int", (.gogoproto.moretags) = "yaml:&#92;"min_self_delegation&#92;""];</code>
     */
    fun clearMinSelfDelegation() {
      _builder.clearMinSelfDelegation()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun cosmos.staking.v1beta1.Tx.MsgEditValidator.copy(block: cosmos.staking.v1beta1.MsgEditValidatorKt.Dsl.() -> Unit): cosmos.staking.v1beta1.Tx.MsgEditValidator =
  cosmos.staking.v1beta1.MsgEditValidatorKt.Dsl._create(this.toBuilder()).apply { block() }._build()
