//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: cosmos/distribution/v1beta1/query.proto

package cosmos.distribution.v1beta1;

@kotlin.jvm.JvmSynthetic
inline fun queryCommunityPoolRequest(block: cosmos.distribution.v1beta1.QueryCommunityPoolRequestKt.Dsl.() -> Unit): cosmos.distribution.v1beta1.QueryOuterClass.QueryCommunityPoolRequest =
  cosmos.distribution.v1beta1.QueryCommunityPoolRequestKt.Dsl._create(cosmos.distribution.v1beta1.QueryOuterClass.QueryCommunityPoolRequest.newBuilder()).apply { block() }._build()
object QueryCommunityPoolRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: cosmos.distribution.v1beta1.QueryOuterClass.QueryCommunityPoolRequest.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: cosmos.distribution.v1beta1.QueryOuterClass.QueryCommunityPoolRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): cosmos.distribution.v1beta1.QueryOuterClass.QueryCommunityPoolRequest = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
inline fun cosmos.distribution.v1beta1.QueryOuterClass.QueryCommunityPoolRequest.copy(block: cosmos.distribution.v1beta1.QueryCommunityPoolRequestKt.Dsl.() -> Unit): cosmos.distribution.v1beta1.QueryOuterClass.QueryCommunityPoolRequest =
  cosmos.distribution.v1beta1.QueryCommunityPoolRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()
