//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: cosmos/upgrade/v1beta1/query.proto

package cosmos.upgrade.v1beta1;

@kotlin.jvm.JvmSynthetic
inline fun queryUpgradedConsensusStateRequest(block: cosmos.upgrade.v1beta1.QueryUpgradedConsensusStateRequestKt.Dsl.() -> Unit): cosmos.upgrade.v1beta1.QueryOuterClass.QueryUpgradedConsensusStateRequest =
  cosmos.upgrade.v1beta1.QueryUpgradedConsensusStateRequestKt.Dsl._create(cosmos.upgrade.v1beta1.QueryOuterClass.QueryUpgradedConsensusStateRequest.newBuilder()).apply { block() }._build()
object QueryUpgradedConsensusStateRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: cosmos.upgrade.v1beta1.QueryOuterClass.QueryUpgradedConsensusStateRequest.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: cosmos.upgrade.v1beta1.QueryOuterClass.QueryUpgradedConsensusStateRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): cosmos.upgrade.v1beta1.QueryOuterClass.QueryUpgradedConsensusStateRequest = _builder.build()

    /**
     * <pre>
     * last height of the current chain must be sent in request
     * as this is the height under which next consensus state is stored
     * </pre>
     *
     * <code>int64 last_height = 1;</code>
     */
    var lastHeight: kotlin.Long
      @JvmName("getLastHeight")
      get() = _builder.getLastHeight()
      @JvmName("setLastHeight")
      set(value) {
        _builder.setLastHeight(value)
      }
    /**
     * <pre>
     * last height of the current chain must be sent in request
     * as this is the height under which next consensus state is stored
     * </pre>
     *
     * <code>int64 last_height = 1;</code>
     */
    fun clearLastHeight() {
      _builder.clearLastHeight()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun cosmos.upgrade.v1beta1.QueryOuterClass.QueryUpgradedConsensusStateRequest.copy(block: cosmos.upgrade.v1beta1.QueryUpgradedConsensusStateRequestKt.Dsl.() -> Unit): cosmos.upgrade.v1beta1.QueryOuterClass.QueryUpgradedConsensusStateRequest =
  cosmos.upgrade.v1beta1.QueryUpgradedConsensusStateRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()
